/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.SqlActualizarDatosPaciente;
import Clases.SqlRegistroPaciente;
import Clases.temporal;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import rojerusan.RSNotifyShadowAnimated;

/**
 *
 * @author Hogar-PC
 */
public class HH_Cambios extends javax.swing.JFrame {
    
    public static FileInputStream imagen;
    public int longitudBytes;

    /**
     * Creates new form HH_Cambios
     */
    public HH_Cambios() {
        initComponents();
        this.setLocationRelativeTo(this);
        temporal tm = new temporal();
        SqlRegistroPaciente.ListarNombrePacienteEditarPerfil(tm.getID());
    }
    
    private void limpiarCampos(){
        TxNombreActualizar.setText("");
        TxApellidoActualizar.setText("");
        TxNumTelefonoActualizar.setText("");
        TxNumCelularActualizar.setText("");
        TxContraseniaActualizar.setText("");
        LbImagenCargar.setIcon(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAgendarCita = new org.edisoncor.gui.panel.Panel();
        jSeparator1 = new javax.swing.JSeparator();
        LbSubtituloAgendarCita = new RSMaterialComponent.RSLabelTextIcon();
        LbGeneroAgendarCita = new javax.swing.JLabel();
        DescripciónDetalladaProblemaAgendarCita = new javax.swing.JLabel();
        LbDisponibilidadAgendarCita = new javax.swing.JLabel();
        LbHoraAgendarCita = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        LbProfesionalSaludAgendarCita = new javax.swing.JLabel();
        LbTipoProblemaAgendarCita = new javax.swing.JLabel();
        LbLogoAppHealtHelp = new javax.swing.JLabel();
        LbTituloHealtHelp = new javax.swing.JLabel();
        LbSloganHealtHelp = new javax.swing.JLabel();
        LbImagenUsuario = new javax.swing.JLabel();
        LbNombrePacienteInterfaz = new javax.swing.JLabel();
        LbCitasAgendadas = new javax.swing.JLabel();
        LbEditarPerfil = new javax.swing.JLabel();
        LbCerrarSesión = new javax.swing.JLabel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        BnActualizarImagenPerfilPaciente = new rojerusan.RSMaterialButtonRectangle();
        LbProfesionalSaludAgendarCita1 = new javax.swing.JLabel();
        LbImagenCargar = new javax.swing.JLabel();
        BnActualizarPerfil = new rojerusan.RSMaterialButtonRectangle();
        BnEliminarCuenta = new rojerusan.RSMaterialButtonRectangle();
        TxNombreActualizar = new RSMaterialComponent.RSTextFieldOne();
        TxApellidoActualizar = new RSMaterialComponent.RSTextFieldOne();
        TxNumTelefonoActualizar = new RSMaterialComponent.RSTextFieldOne();
        TxNumCelularActualizar = new RSMaterialComponent.RSTextFieldOne();
        TxContraseniaActualizar = new RSMaterialComponent.RSPasswordOne();
        BnVolver = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAgendarCita.setColorPrimario(new java.awt.Color(0, 102, 153));
        PanelAgendarCita.setColorSecundario(new java.awt.Color(0, 153, 102));
        PanelAgendarCita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelAgendarCita.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 189, -1, -1));

        LbSubtituloAgendarCita.setForeground(new java.awt.Color(6, 52, 86));
        LbSubtituloAgendarCita.setText("¡Realiza cambios en tu perfil!");
        LbSubtituloAgendarCita.setFont(new java.awt.Font("Sitka Banner", 1, 32)); // NOI18N
        LbSubtituloAgendarCita.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DATE_RANGE);
        PanelAgendarCita.add(LbSubtituloAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 920, -1));

        LbGeneroAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbGeneroAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbGeneroAgendarCita.setText("Nímero de celular:");
        PanelAgendarCita.add(LbGeneroAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 220, -1));

        DescripciónDetalladaProblemaAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        DescripciónDetalladaProblemaAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        DescripciónDetalladaProblemaAgendarCita.setText("Foto de perfil");
        PanelAgendarCita.add(DescripciónDetalladaProblemaAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 260, -1));

        LbDisponibilidadAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbDisponibilidadAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbDisponibilidadAgendarCita.setText("Apellido:");
        PanelAgendarCita.add(LbDisponibilidadAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 220, -1));

        LbHoraAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbHoraAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbHoraAgendarCita.setText("Número de teléfono:");
        PanelAgendarCita.add(LbHoraAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 220, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        PanelAgendarCita.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 10, 320));

        LbProfesionalSaludAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbProfesionalSaludAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbProfesionalSaludAgendarCita.setText("Nombre:");
        PanelAgendarCita.add(LbProfesionalSaludAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 220, -1));

        LbTipoProblemaAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbTipoProblemaAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbTipoProblemaAgendarCita.setText("Contraseña");
        PanelAgendarCita.add(LbTipoProblemaAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 220, -1));

        LbLogoAppHealtHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal.jpg"))); // NOI18N
        LbLogoAppHealtHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbLogoAppHealtHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbLogoAppHealtHelpMouseClicked(evt);
            }
        });
        PanelAgendarCita.add(LbLogoAppHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        LbTituloHealtHelp.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        LbTituloHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbTituloHealtHelp.setText("HealtHelp");
        PanelAgendarCita.add(LbTituloHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        LbSloganHealtHelp.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        LbSloganHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbSloganHealtHelp.setText("Tu salud en nuestras manos ");
        PanelAgendarCita.add(LbSloganHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 15));

        LbImagenUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Foto usuario.png"))); // NOI18N
        PanelAgendarCita.add(LbImagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 40, 40));

        LbNombrePacienteInterfaz.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbNombrePacienteInterfaz.setForeground(new java.awt.Color(255, 255, 255));
        LbNombrePacienteInterfaz.setText("Rosendo Bucuru");
        PanelAgendarCita.add(LbNombrePacienteInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 180, 40));

        LbCitasAgendadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCitasAgendadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.png"))); // NOI18N
        LbCitasAgendadas.setToolTipText("CITAS AGENDADAS");
        LbCitasAgendadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbCitasAgendadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCitasAgendadasMouseClicked(evt);
            }
        });
        PanelAgendarCita.add(LbCitasAgendadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 40, 40));

        LbEditarPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-pequeño.png"))); // NOI18N
        LbEditarPerfil.setToolTipText("EDITAR PERFIL");
        LbEditarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbEditarPerfilMouseClicked(evt);
            }
        });
        PanelAgendarCita.add(LbEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 40, 40));

        LbCerrarSesión.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCerrarSesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion-pequeño.png"))); // NOI18N
        LbCerrarSesión.setToolTipText("CERRAR SESIÓN");
        LbCerrarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbCerrarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCerrarSesiónMouseClicked(evt);
            }
        });
        PanelAgendarCita.add(LbCerrarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 40, 40));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panel1.setForeground(new java.awt.Color(255, 255, 255));
        panel1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BnActualizarImagenPerfilPaciente.setBackground(new java.awt.Color(255, 255, 255));
        BnActualizarImagenPerfilPaciente.setForeground(new java.awt.Color(0, 0, 0));
        BnActualizarImagenPerfilPaciente.setText("EXAMINAR");
        BnActualizarImagenPerfilPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnActualizarImagenPerfilPacienteActionPerformed(evt);
            }
        });
        panel1.add(BnActualizarImagenPerfilPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 80, 35));

        LbProfesionalSaludAgendarCita1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbProfesionalSaludAgendarCita1.setForeground(new java.awt.Color(178, 181, 244));
        LbProfesionalSaludAgendarCita1.setText("Cargar imagen perfil");
        panel1.add(LbProfesionalSaludAgendarCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 130, 35));

        LbImagenCargar.setFont(new java.awt.Font("Algerian", 2, 16)); // NOI18N
        LbImagenCargar.setForeground(new java.awt.Color(255, 255, 255));
        panel1.add(LbImagenCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 35));

        PanelAgendarCita.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 260, 35));

        BnActualizarPerfil.setBackground(new java.awt.Color(255, 255, 255));
        BnActualizarPerfil.setForeground(new java.awt.Color(0, 0, 0));
        BnActualizarPerfil.setText("ACTUALIZAR");
        BnActualizarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnActualizarPerfilActionPerformed(evt);
            }
        });
        PanelAgendarCita.add(BnActualizarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 140, 50));

        BnEliminarCuenta.setBackground(new java.awt.Color(255, 255, 255));
        BnEliminarCuenta.setForeground(new java.awt.Color(0, 0, 0));
        BnEliminarCuenta.setText("ELIMINAR CUENTA");
        BnEliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnEliminarCuentaActionPerformed(evt);
            }
        });
        PanelAgendarCita.add(BnEliminarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 150, 50));

        TxNombreActualizar.setForeground(new java.awt.Color(0, 0, 0));
        TxNombreActualizar.setBorderColor(new java.awt.Color(255, 255, 255));
        TxNombreActualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxNombreActualizar.setPlaceholder("Escribe aquí...");
        PanelAgendarCita.add(TxNombreActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 260, 35));

        TxApellidoActualizar.setForeground(new java.awt.Color(0, 0, 0));
        TxApellidoActualizar.setBorderColor(new java.awt.Color(255, 255, 255));
        TxApellidoActualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxApellidoActualizar.setPlaceholder("Escribe aquí...");
        TxApellidoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxApellidoActualizarActionPerformed(evt);
            }
        });
        PanelAgendarCita.add(TxApellidoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 260, 35));

        TxNumTelefonoActualizar.setForeground(new java.awt.Color(0, 0, 0));
        TxNumTelefonoActualizar.setBorderColor(new java.awt.Color(255, 255, 255));
        TxNumTelefonoActualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxNumTelefonoActualizar.setPlaceholder("Escribe aquí...");
        PanelAgendarCita.add(TxNumTelefonoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 260, 35));

        TxNumCelularActualizar.setForeground(new java.awt.Color(0, 0, 0));
        TxNumCelularActualizar.setBorderColor(new java.awt.Color(255, 255, 255));
        TxNumCelularActualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxNumCelularActualizar.setPlaceholder("Escribe aquí...");
        PanelAgendarCita.add(TxNumCelularActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 260, 35));

        TxContraseniaActualizar.setForeground(new java.awt.Color(0, 0, 0));
        TxContraseniaActualizar.setBorderColor(new java.awt.Color(255, 255, 255));
        TxContraseniaActualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxContraseniaActualizar.setPlaceholder("Escribe aquí...");
        PanelAgendarCita.add(TxContraseniaActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 260, 35));

        BnVolver.setBackground(new java.awt.Color(255, 255, 255));
        BnVolver.setForeground(new java.awt.Color(0, 0, 0));
        BnVolver.setText("VOLVER");
        BnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnVolverActionPerformed(evt);
            }
        });
        PanelAgendarCita.add(BnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 140, 50));

        getContentPane().add(PanelAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 922, 643));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LbCitasAgendadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCitasAgendadasMouseClicked

        HH_TablaCitasPaciente citasAgendadas = new HH_TablaCitasPaciente();
        citasAgendadas.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbCitasAgendadasMouseClicked

    private void LbEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbEditarPerfilMouseClicked
        temporal tm= new temporal();
        SqlActualizarDatosPaciente.buscarDatos(tm.getID());
        
    }//GEN-LAST:event_LbEditarPerfilMouseClicked

    private void LbCerrarSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCerrarSesiónMouseClicked

        MenuEntrada menu = new MenuEntrada();
        menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbCerrarSesiónMouseClicked

    private void BnActualizarImagenPerfilPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnActualizarImagenPerfilPacienteActionPerformed

        JFileChooser se = new JFileChooser();
        FileNameExtensionFilter extension = new FileNameExtensionFilter("JPG, PNG & GIF","jpg","png","gif");
        se.setFileFilter(extension);
        int estado = se.showOpenDialog(this);
        System.out.print(estado);
        if(estado == JFileChooser.APPROVE_OPTION)
        {
            try {

                imagen =  new FileInputStream(se.getSelectedFile());
                longitudBytes = (int)se.getSelectedFile().length();

                Image icono = ImageIO.read(se.getSelectedFile()).getScaledInstance(LbImagenCargar.getWidth(), LbImagenCargar.getHeight(), Image.SCALE_DEFAULT);
                LbImagenCargar.setIcon(new ImageIcon(icono));
                LbImagenCargar.updateUI();

            } catch (FileNotFoundException ex) {ex.printStackTrace();}
            catch (IOException ex){ex.printStackTrace();}
        }

    }//GEN-LAST:event_BnActualizarImagenPerfilPacienteActionPerformed

    private void BnActualizarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnActualizarPerfilActionPerformed
         temporal tm = new temporal();
         int opcion = SqlActualizarDatosPaciente.editarPerfilPaciente(tm.getID());
         if(opcion > 0){
                new rojerusan.RSNotifyShadowAnimated("!Hecho¡",
                                    "!Registro éxitoso!", 
                                    3, 
                                    RSNotifyShadowAnimated.PositionNotify.TopRight, 
                                    RSNotifyShadowAnimated.AnimationNotify.UpBottom, 
                                    RSNotifyShadowAnimated.TypeNotify.SUCCESS).setVisible(true);
                
               
                limpiarCampos();
            } else {
                new rojerusan.RSNotifyShadowAnimated("!Intente de nuevo¡",
                                    "!Problemas  al guardar el registro!", 
                                    3, 
                                    RSNotifyShadowAnimated.PositionNotify.TopRight, 
                                    RSNotifyShadowAnimated.AnimationNotify.UpBottom, 
                                    RSNotifyShadowAnimated.TypeNotify.WARNING).setVisible(true);
               
                limpiarCampos();
            }
 
    }//GEN-LAST:event_BnActualizarPerfilActionPerformed

    private void LbLogoAppHealtHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbLogoAppHealtHelpMouseClicked
    
        HhAgendarCita principal = new HhAgendarCita();
        principal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_LbLogoAppHealtHelpMouseClicked

    private void BnEliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnEliminarCuentaActionPerformed
       
        
        /*int confirmar=JOptionPane.showConfirmDialog(this, "¿Esta seguro de eliminar el usuario?");
                    if(confirmar==0){
                        temporal tm = new temporal();
                        int elimina = SqlActualizarDatosPaciente.eliminar(tm.getID());
                        if(elimina > 0){
                            
                            new rojerusan.RSNotifyShadowAnimated("!Hecho¡",
                                    "!Eliminado éxitosamente!", 
                                    3, 
                                    RSNotifyShadowAnimated.PositionNotify.TopRight, 
                                    RSNotifyShadowAnimated.AnimationNotify.UpBottom, 
                                    RSNotifyShadowAnimated.TypeNotify.SUCCESS).setVisible(true);
                            limpiarCampos();
                            MenuEntrada inicio = new MenuEntrada();
                            inicio.setVisible(true);
                            this.dispose();
                            
                        } else {
                          
                            new rojerusan.RSNotifyShadowAnimated("!Intente de nuevo¡",
                                    "!Problemas  al eliminar el registro!", 
                                    3, 
                                    RSNotifyShadowAnimated.PositionNotify.TopRight, 
                                    RSNotifyShadowAnimated.AnimationNotify.UpBottom, 
                                    RSNotifyShadowAnimated.TypeNotify.WARNING).setVisible(true);
                        
                        }
                      }*/
        
    }//GEN-LAST:event_BnEliminarCuentaActionPerformed

    private void TxApellidoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxApellidoActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxApellidoActualizarActionPerformed

    private void BnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnVolverActionPerformed
        HhAgendarCita principal = new HhAgendarCita();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HH_Cambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HH_Cambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HH_Cambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HH_Cambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HH_Cambios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle BnActualizarImagenPerfilPaciente;
    private rojerusan.RSMaterialButtonRectangle BnActualizarPerfil;
    private rojerusan.RSMaterialButtonRectangle BnEliminarCuenta;
    private rojerusan.RSMaterialButtonRectangle BnVolver;
    private javax.swing.JLabel DescripciónDetalladaProblemaAgendarCita;
    private javax.swing.JLabel LbCerrarSesión;
    private javax.swing.JLabel LbCitasAgendadas;
    private javax.swing.JLabel LbDisponibilidadAgendarCita;
    private javax.swing.JLabel LbEditarPerfil;
    private javax.swing.JLabel LbGeneroAgendarCita;
    private javax.swing.JLabel LbHoraAgendarCita;
    public static javax.swing.JLabel LbImagenCargar;
    public static javax.swing.JLabel LbImagenUsuario;
    private javax.swing.JLabel LbLogoAppHealtHelp;
    public static javax.swing.JLabel LbNombrePacienteInterfaz;
    private javax.swing.JLabel LbProfesionalSaludAgendarCita;
    private javax.swing.JLabel LbProfesionalSaludAgendarCita1;
    private javax.swing.JLabel LbSloganHealtHelp;
    private RSMaterialComponent.RSLabelTextIcon LbSubtituloAgendarCita;
    private javax.swing.JLabel LbTipoProblemaAgendarCita;
    private javax.swing.JLabel LbTituloHealtHelp;
    private org.edisoncor.gui.panel.Panel PanelAgendarCita;
    public static RSMaterialComponent.RSTextFieldOne TxApellidoActualizar;
    public static RSMaterialComponent.RSPasswordOne TxContraseniaActualizar;
    public static RSMaterialComponent.RSTextFieldOne TxNombreActualizar;
    public static RSMaterialComponent.RSTextFieldOne TxNumCelularActualizar;
    public static RSMaterialComponent.RSTextFieldOne TxNumTelefonoActualizar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
