/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Juan Mguel
 */
public class HH_ErrorContrasenia extends javax.swing.JFrame {

    /**
     * Creates new form HH_ErrorContrasenia
     */
    public HH_ErrorContrasenia() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondoErrorContraseña = new org.edisoncor.gui.panel.Panel();
        BnVolverErrorContraseña = new javax.swing.JButton();
        BnRegistrarseErrorContraseña = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondoErrorContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Error-Contraseña-Editado.gif"))); // NOI18N
        PanelFondoErrorContraseña.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BnVolverErrorContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonVolver.png"))); // NOI18N
        BnVolverErrorContraseña.setBorder(null);
        BnVolverErrorContraseña.setBorderPainted(false);
        BnVolverErrorContraseña.setContentAreaFilled(false);
        BnVolverErrorContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BnVolverErrorContraseña.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonVolver2 .png"))); // NOI18N
        BnVolverErrorContraseña.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonVolver2 .png"))); // NOI18N
        BnVolverErrorContraseña.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonVolver2 .png"))); // NOI18N
        BnVolverErrorContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnVolverErrorContraseñaActionPerformed(evt);
            }
        });
        PanelFondoErrorContraseña.add(BnVolverErrorContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 200, 70));

        BnRegistrarseErrorContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotónRegistrarse.png"))); // NOI18N
        BnRegistrarseErrorContraseña.setBorder(null);
        BnRegistrarseErrorContraseña.setBorderPainted(false);
        BnRegistrarseErrorContraseña.setContentAreaFilled(false);
        BnRegistrarseErrorContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BnRegistrarseErrorContraseña.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonRegistrarse2.png"))); // NOI18N
        BnRegistrarseErrorContraseña.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonRegistrarse2.png"))); // NOI18N
        BnRegistrarseErrorContraseña.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonRegistrarse2.png"))); // NOI18N
        BnRegistrarseErrorContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnRegistrarseErrorContraseñaActionPerformed(evt);
            }
        });
        PanelFondoErrorContraseña.add(BnRegistrarseErrorContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 180, 70));

        getContentPane().add(PanelFondoErrorContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnVolverErrorContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnVolverErrorContraseñaActionPerformed

        Iniciar_Sesion_HH iniciarsesionhh = new Iniciar_Sesion_HH();
        iniciarsesionhh.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BnVolverErrorContraseñaActionPerformed

    private void BnRegistrarseErrorContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnRegistrarseErrorContraseñaActionPerformed

        HH_ElegirCuenta registrohp = new HH_ElegirCuenta();
        registrohp.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BnRegistrarseErrorContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HH_ErrorContrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HH_ErrorContrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HH_ErrorContrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HH_ErrorContrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HH_ErrorContrasenia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnRegistrarseErrorContraseña;
    private javax.swing.JButton BnVolverErrorContraseña;
    private org.edisoncor.gui.panel.Panel PanelFondoErrorContraseña;
    // End of variables declaration//GEN-END:variables
}
