/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.SqlActualizarDatosPaciente;
import Clases.SqlRegistroMedico;
import Clases.temporal;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import rojerusan.RSNotifyShadowAnimated;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class HH_EditarPerfilMedico extends javax.swing.JFrame {

    public static FileInputStream imagen;
    public int longitudBytes;

    /**
     * Creates new form HH_EditarPerfilMedico
     */
    public HH_EditarPerfilMedico() {
        initComponents();
        this.setLocationRelativeTo(this);
        temporal tm = new temporal();
        SqlRegistroMedico.listarNombreMedicoEditarPerfil(tm.getID());
    }

    private void limpiarCampos() {
        TxNombre.setText("");
        TxApellido.setText("");
        TxEpsDondeTrabaja.setText("");
        TxNumeroCelular.setText("");
        TxContraseña.setText("");
        LbImagenCargar.setIcon(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEditarPerfilMedico = new org.edisoncor.gui.panel.Panel();
        jSeparator1 = new javax.swing.JSeparator();
        LbSubtituloAgendarCita = new RSMaterialComponent.RSLabelTextIcon();
        LbGeneroAgendarCita = new javax.swing.JLabel();
        DescripciónDetalladaProblemaAgendarCita = new javax.swing.JLabel();
        LbDisponibilidadAgendarCita = new javax.swing.JLabel();
        LbHoraAgendarCita = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        LbProfesionalSaludAgendarCita = new javax.swing.JLabel();
        LbTipoProblemaAgendarCita = new javax.swing.JLabel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        BnActualizarImagenPerfilPaciente = new rojerusan.RSMaterialButtonRectangle();
        LbProfesionalSaludAgendarCita1 = new javax.swing.JLabel();
        LbImagenCargar = new javax.swing.JLabel();
        BnActualizarPerfil = new rojerusan.RSMaterialButtonRectangle();
        BnVolver = new rojerusan.RSMaterialButtonRectangle();
        LbImagenAppHealtHelp = new javax.swing.JLabel();
        LbHealtHelp = new javax.swing.JLabel();
        LbSloganHealtHelp = new javax.swing.JLabel();
        LbImagenDoctor = new javax.swing.JLabel();
        LbNombreDoctorInterfaz = new javax.swing.JLabel();
        LbEditarPerfil = new javax.swing.JLabel();
        LbCerrarSesión = new javax.swing.JLabel();
        TxContraseña = new RSMaterialComponent.RSPasswordOne();
        TxNumeroCelular = new RSMaterialComponent.RSTextFieldOne();
        TxNombre = new RSMaterialComponent.RSTextFieldOne();
        TxEpsDondeTrabaja = new RSMaterialComponent.RSTextFieldOne();
        TxApellido = new RSMaterialComponent.RSTextFieldOne();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        PanelEditarPerfilMedico.setColorPrimario(new java.awt.Color(0, 102, 153));
        PanelEditarPerfilMedico.setColorSecundario(new java.awt.Color(0, 153, 102));
        PanelEditarPerfilMedico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelEditarPerfilMedico.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 189, -1, -1));

        LbSubtituloAgendarCita.setForeground(new java.awt.Color(6, 52, 86));
        LbSubtituloAgendarCita.setText("¡Realiza cambios en tu perfil!");
        LbSubtituloAgendarCita.setFont(new java.awt.Font("Sitka Banner", 1, 32)); // NOI18N
        LbSubtituloAgendarCita.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DATE_RANGE);
        PanelEditarPerfilMedico.add(LbSubtituloAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 920, -1));

        LbGeneroAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbGeneroAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbGeneroAgendarCita.setText("Nímero de celular:");
        PanelEditarPerfilMedico.add(LbGeneroAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 220, -1));

        DescripciónDetalladaProblemaAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        DescripciónDetalladaProblemaAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        DescripciónDetalladaProblemaAgendarCita.setText("Foto de perfil");
        PanelEditarPerfilMedico.add(DescripciónDetalladaProblemaAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 260, -1));

        LbDisponibilidadAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbDisponibilidadAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbDisponibilidadAgendarCita.setText("Apellido:");
        PanelEditarPerfilMedico.add(LbDisponibilidadAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 220, -1));

        LbHoraAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbHoraAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbHoraAgendarCita.setText("Eps donde trabaja:");
        PanelEditarPerfilMedico.add(LbHoraAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 220, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        PanelEditarPerfilMedico.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 10, 320));

        LbProfesionalSaludAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbProfesionalSaludAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbProfesionalSaludAgendarCita.setText("Nombre:");
        PanelEditarPerfilMedico.add(LbProfesionalSaludAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 220, -1));

        LbTipoProblemaAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbTipoProblemaAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbTipoProblemaAgendarCita.setText("Contraseña");
        PanelEditarPerfilMedico.add(LbTipoProblemaAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 220, -1));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panel1.setForeground(new java.awt.Color(255, 255, 255));
        panel1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BnActualizarImagenPerfilPaciente.setBackground(new java.awt.Color(255, 255, 255));
        BnActualizarImagenPerfilPaciente.setForeground(new java.awt.Color(0, 0, 0));
        BnActualizarImagenPerfilPaciente.setText("EXAMINAR");
        BnActualizarImagenPerfilPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnActualizarImagenPerfilPacienteActionPerformed(evt);
            }
        });
        panel1.add(BnActualizarImagenPerfilPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 80, 35));

        LbProfesionalSaludAgendarCita1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbProfesionalSaludAgendarCita1.setForeground(new java.awt.Color(178, 181, 244));
        LbProfesionalSaludAgendarCita1.setText("Cargar imagen perfil");
        panel1.add(LbProfesionalSaludAgendarCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 130, 35));

        LbImagenCargar.setFont(new java.awt.Font("Algerian", 2, 16)); // NOI18N
        LbImagenCargar.setForeground(new java.awt.Color(255, 255, 255));
        panel1.add(LbImagenCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 35));

        PanelEditarPerfilMedico.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 260, 35));

        BnActualizarPerfil.setBackground(new java.awt.Color(255, 255, 255));
        BnActualizarPerfil.setForeground(new java.awt.Color(0, 0, 0));
        BnActualizarPerfil.setText("ACTUALIZAR");
        BnActualizarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnActualizarPerfilActionPerformed(evt);
            }
        });
        PanelEditarPerfilMedico.add(BnActualizarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 140, 50));

        BnVolver.setBackground(new java.awt.Color(255, 255, 255));
        BnVolver.setForeground(new java.awt.Color(0, 0, 0));
        BnVolver.setText("VOLVER");
        BnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnVolverActionPerformed(evt);
            }
        });
        PanelEditarPerfilMedico.add(BnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 140, 50));

        LbImagenAppHealtHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal.jpg"))); // NOI18N
        PanelEditarPerfilMedico.add(LbImagenAppHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        LbHealtHelp.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        LbHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbHealtHelp.setText("HealtHelp");
        PanelEditarPerfilMedico.add(LbHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        LbSloganHealtHelp.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        LbSloganHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbSloganHealtHelp.setText("Tu salud en nuestras manos ");
        PanelEditarPerfilMedico.add(LbSloganHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 15));

        LbImagenDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbImagenDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Foto usuario.png"))); // NOI18N
        PanelEditarPerfilMedico.add(LbImagenDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 40, 40));

        LbNombreDoctorInterfaz.setFont(new java.awt.Font("Sitka Banner", 1, 22)); // NOI18N
        LbNombreDoctorInterfaz.setForeground(new java.awt.Color(255, 255, 255));
        LbNombreDoctorInterfaz.setText("Dr. Armando Mendoza");
        PanelEditarPerfilMedico.add(LbNombreDoctorInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 220, 40));

        LbEditarPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-pequeño.png"))); // NOI18N
        LbEditarPerfil.setToolTipText("EDITAR PERFIL");
        LbEditarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbEditarPerfilMouseClicked(evt);
            }
        });
        PanelEditarPerfilMedico.add(LbEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 40, 40));

        LbCerrarSesión.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCerrarSesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion-pequeño.png"))); // NOI18N
        LbCerrarSesión.setToolTipText("CERRAR SESIÓN");
        LbCerrarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbCerrarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCerrarSesiónMouseClicked(evt);
            }
        });
        PanelEditarPerfilMedico.add(LbCerrarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 40, 40));

        TxContraseña.setBorder(null);
        TxContraseña.setForeground(new java.awt.Color(0, 0, 0));
        TxContraseña.setBorderColor(new java.awt.Color(255, 255, 255));
        TxContraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxContraseña.setPlaceholder("Escribe aquí...");
        PanelEditarPerfilMedico.add(TxContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 260, 35));

        TxNumeroCelular.setForeground(new java.awt.Color(0, 0, 0));
        TxNumeroCelular.setBorderColor(new java.awt.Color(255, 255, 255));
        TxNumeroCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxNumeroCelular.setPlaceholder("Escribe aquí...");
        PanelEditarPerfilMedico.add(TxNumeroCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 260, 35));

        TxNombre.setForeground(new java.awt.Color(0, 0, 0));
        TxNombre.setBorderColor(new java.awt.Color(255, 255, 255));
        TxNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxNombre.setPlaceholder("Escribe aquí...");
        PanelEditarPerfilMedico.add(TxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 260, 35));

        TxEpsDondeTrabaja.setForeground(new java.awt.Color(0, 0, 0));
        TxEpsDondeTrabaja.setBorderColor(new java.awt.Color(255, 255, 255));
        TxEpsDondeTrabaja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxEpsDondeTrabaja.setPlaceholder("Escribe aquí...");
        PanelEditarPerfilMedico.add(TxEpsDondeTrabaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 260, 35));

        TxApellido.setForeground(new java.awt.Color(0, 0, 0));
        TxApellido.setBorderColor(new java.awt.Color(255, 255, 255));
        TxApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxApellido.setPlaceholder("Escribe aquí...");
        TxApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxApellidoActionPerformed(evt);
            }
        });
        PanelEditarPerfilMedico.add(TxApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 260, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelEditarPerfilMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelEditarPerfilMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnActualizarImagenPerfilPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnActualizarImagenPerfilPacienteActionPerformed

        JFileChooser se = new JFileChooser();
        FileNameExtensionFilter extension = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        se.setFileFilter(extension);
        int estado = se.showOpenDialog(this);
        System.out.print(estado);
        if (estado == JFileChooser.APPROVE_OPTION) {
            try {

                imagen = new FileInputStream(se.getSelectedFile());
                longitudBytes = (int) se.getSelectedFile().length();

                Image icono = ImageIO.read(se.getSelectedFile()).getScaledInstance(LbImagenCargar.getWidth(), LbImagenCargar.getHeight(), Image.SCALE_DEFAULT);
                LbImagenCargar.setIcon(new ImageIcon(icono));
                LbImagenCargar.updateUI();

            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_BnActualizarImagenPerfilPacienteActionPerformed

    private void BnActualizarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnActualizarPerfilActionPerformed
        temporal tm = new temporal();
        int opcion = SqlActualizarDatosPaciente.editarPerfilMedico(tm.getID());
        if (opcion > 0) {
            new rojerusan.RSNotifyShadowAnimated("!Hecho¡",
                    "!Registro éxitoso!",
                    3,
                    RSNotifyShadowAnimated.PositionNotify.TopRight,
                    RSNotifyShadowAnimated.AnimationNotify.UpBottom,
                    RSNotifyShadowAnimated.TypeNotify.SUCCESS).setVisible(true);

            limpiarCampos();
        } else {
            new rojerusan.RSNotifyShadowAnimated("!Intente de nuevo¡",
                    "!Problemas  al guardar el registro!",
                    3,
                    RSNotifyShadowAnimated.PositionNotify.TopRight,
                    RSNotifyShadowAnimated.AnimationNotify.UpBottom,
                    RSNotifyShadowAnimated.TypeNotify.WARNING).setVisible(true);

            limpiarCampos();
        }

    }//GEN-LAST:event_BnActualizarPerfilActionPerformed

    private void BnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnVolverActionPerformed

        HH_PerfilMédico medico = new HH_PerfilMédico();
        medico.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BnVolverActionPerformed

    private void LbEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbEditarPerfilMouseClicked
        HH_EditarPerfilMedico editar = new HH_EditarPerfilMedico();
        editar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbEditarPerfilMouseClicked

    private void LbCerrarSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCerrarSesiónMouseClicked
        MenuEntrada menu = new MenuEntrada();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbCerrarSesiónMouseClicked

    private void TxApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxApellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HH_EditarPerfilMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HH_EditarPerfilMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HH_EditarPerfilMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HH_EditarPerfilMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HH_EditarPerfilMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle BnActualizarImagenPerfilPaciente;
    private rojerusan.RSMaterialButtonRectangle BnActualizarPerfil;
    private rojerusan.RSMaterialButtonRectangle BnVolver;
    private javax.swing.JLabel DescripciónDetalladaProblemaAgendarCita;
    private javax.swing.JLabel LbCerrarSesión;
    private javax.swing.JLabel LbDisponibilidadAgendarCita;
    private javax.swing.JLabel LbEditarPerfil;
    private javax.swing.JLabel LbGeneroAgendarCita;
    private javax.swing.JLabel LbHealtHelp;
    private javax.swing.JLabel LbHoraAgendarCita;
    private javax.swing.JLabel LbImagenAppHealtHelp;
    public static javax.swing.JLabel LbImagenCargar;
    public static javax.swing.JLabel LbImagenDoctor;
    public static javax.swing.JLabel LbNombreDoctorInterfaz;
    private javax.swing.JLabel LbProfesionalSaludAgendarCita;
    private javax.swing.JLabel LbProfesionalSaludAgendarCita1;
    private javax.swing.JLabel LbSloganHealtHelp;
    private RSMaterialComponent.RSLabelTextIcon LbSubtituloAgendarCita;
    private javax.swing.JLabel LbTipoProblemaAgendarCita;
    private org.edisoncor.gui.panel.Panel PanelEditarPerfilMedico;
    public static RSMaterialComponent.RSTextFieldOne TxApellido;
    public static RSMaterialComponent.RSPasswordOne TxContraseña;
    public static RSMaterialComponent.RSTextFieldOne TxEpsDondeTrabaja;
    public static RSMaterialComponent.RSTextFieldOne TxNombre;
    public static RSMaterialComponent.RSTextFieldOne TxNumeroCelular;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
