/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Juan Mguel
 */
public class HH_ElegirCuenta extends javax.swing.JFrame {

    /**
     * Creates new form HH_ElegirCuenta
     */
    public HH_ElegirCuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelElijaPerfil = new org.edisoncor.gui.panel.Panel();
        jSeparator1 = new javax.swing.JSeparator();
        LbTituloElijaPerfil = new javax.swing.JLabel();
        Separador = new javax.swing.JSeparator();
        LbDoctor = new javax.swing.JLabel();
        LbImagenDoctor = new javax.swing.JLabel();
        LbUsuario = new javax.swing.JLabel();
        LbImagenUsuario = new javax.swing.JLabel();
        LbMinimizar = new javax.swing.JLabel();
        LbSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        PanelElijaPerfil.setColorPrimario(new java.awt.Color(0, 102, 153));
        PanelElijaPerfil.setColorSecundario(new java.awt.Color(0, 153, 102));
        PanelElijaPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelElijaPerfil.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 189, -1, -1));

        LbTituloElijaPerfil.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        LbTituloElijaPerfil.setForeground(new java.awt.Color(255, 255, 255));
        LbTituloElijaPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbTituloElijaPerfil.setText("ELIJA SU PERFIL");
        PanelElijaPerfil.add(LbTituloElijaPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 360, 43));
        PanelElijaPerfil.add(Separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 410, 10));

        LbDoctor.setFont(new java.awt.Font("Century Gothic", 1, 32)); // NOI18N
        LbDoctor.setForeground(new java.awt.Color(255, 255, 255));
        LbDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbDoctor.setText("DOCTOR");
        LbDoctor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbDoctorMouseClicked(evt);
            }
        });
        PanelElijaPerfil.add(LbDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 150, 50));

        LbImagenDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbImagenDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Doc.png"))); // NOI18N
        LbImagenDoctor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbImagenDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbImagenDoctorMouseClicked(evt);
            }
        });
        PanelElijaPerfil.add(LbImagenDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, 100));

        LbUsuario.setFont(new java.awt.Font("Century Gothic", 1, 32)); // NOI18N
        LbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LbUsuario.setText("USUARIO");
        LbUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbUsuarioMouseClicked(evt);
            }
        });
        PanelElijaPerfil.add(LbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 150, 50));

        LbImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Paciente.png"))); // NOI18N
        LbImagenUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbImagenUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbImagenUsuarioMouseClicked(evt);
            }
        });
        PanelElijaPerfil.add(LbImagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        LbMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar (1).png"))); // NOI18N
        LbMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbMinimizarMouseClicked(evt);
            }
        });
        PanelElijaPerfil.add(LbMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 40, 40));

        LbSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir (1).png"))); // NOI18N
        LbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbSalirMouseClicked(evt);
            }
        });
        PanelElijaPerfil.add(LbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelElijaPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelElijaPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LbDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbDoctorMouseClicked

        RegistroHH_Medico registrarsehhmedico = new RegistroHH_Medico();
        registrarsehhmedico.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbDoctorMouseClicked

    private void LbImagenDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbImagenDoctorMouseClicked

        RegistroHH_Medico registrarsehhmedico = new RegistroHH_Medico();
        registrarsehhmedico.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbImagenDoctorMouseClicked

    private void LbUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbUsuarioMouseClicked

        RegistroHP registrohp = new RegistroHP();
        registrohp.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbUsuarioMouseClicked

    private void LbImagenUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbImagenUsuarioMouseClicked

        RegistroHP registrohp = new RegistroHP();
        registrohp.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbImagenUsuarioMouseClicked

    private void LbMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbMinimizarMouseClicked

        this.setState(MenuEntrada.ICONIFIED);
    }//GEN-LAST:event_LbMinimizarMouseClicked

    private void LbSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbSalirMouseClicked

        System.exit(0);
    }//GEN-LAST:event_LbSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HH_ElegirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HH_ElegirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HH_ElegirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HH_ElegirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HH_ElegirCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbDoctor;
    private javax.swing.JLabel LbImagenDoctor;
    private javax.swing.JLabel LbImagenUsuario;
    private javax.swing.JLabel LbMinimizar;
    private javax.swing.JLabel LbSalir;
    private javax.swing.JLabel LbTituloElijaPerfil;
    private javax.swing.JLabel LbUsuario;
    private org.edisoncor.gui.panel.Panel PanelElijaPerfil;
    private javax.swing.JSeparator Separador;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
