    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.SplashScreen;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Mguel
 */
public class HH_InterfazDeCarga extends javax.swing.JFrame {

    /**
     * Creates new form HH_InterfazDeCarga
     */
    public HH_InterfazDeCarga() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAgendarCita = new org.edisoncor.gui.panel.Panel();
        jSeparator1 = new javax.swing.JSeparator();
        LbLogo = new javax.swing.JLabel();
        LbSloganHealtHelp = new javax.swing.JLabel();
        LbTituloHealtHelp = new javax.swing.JLabel();
        BarraCarga = new javax.swing.JProgressBar();
        LoadingLable = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        PanelAgendarCita.setColorPrimario(new java.awt.Color(0, 102, 153));
        PanelAgendarCita.setColorSecundario(new java.awt.Color(0, 153, 102));
        PanelAgendarCita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelAgendarCita.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 189, -1, -1));

        LbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoAppGRANDERecortado.png"))); // NOI18N
        PanelAgendarCita.add(LbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 280, 290));

        LbSloganHealtHelp.setFont(new java.awt.Font("Segoe Script", 3, 20)); // NOI18N
        LbSloganHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbSloganHealtHelp.setText("Tu salud en nuestras manos ");
        PanelAgendarCita.add(LbSloganHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, 15));

        LbTituloHealtHelp.setFont(new java.awt.Font("Segoe UI", 1, 75)); // NOI18N
        LbTituloHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbTituloHealtHelp.setText("HEALTHELP");
        PanelAgendarCita.add(LbTituloHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));
        PanelAgendarCita.add(BarraCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 860, 10));

        LoadingLable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoadingLable.setForeground(new java.awt.Color(255, 255, 255));
        LoadingLable.setText("Cargando...");
        PanelAgendarCita.add(LoadingLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 220, -1));

        LoadingValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setText("0%");
        PanelAgendarCita.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 40, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAgendarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAgendarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HH_InterfazDeCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HH_InterfazDeCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HH_InterfazDeCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HH_InterfazDeCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       HH_InterfazDeCarga sp = new HH_InterfazDeCarga();
       sp.setVisible(true);
       
       
       try {
        
           
           for(int i=0;i<=100;i++){
               Thread.sleep(35);
           sp.LoadingValue.setText(i+"%");
           
           if (i==10){
               sp.LoadingLable.setText("Cargando modulos...");
           }
           if (i==20){
               sp.LoadingLable.setText("Conectando base de datos...");
           }
           if (i==50){
               sp.LoadingLable.setText("Descargando datos...");
           }
           if (i==70){
               sp.LoadingLable.setText("Conección completada...");
           }
           if (i==80){
               sp.LoadingLable.setText("Abriendo aplicación...");
           }
           sp.BarraCarga.setValue(i);
           
           if (i==100){
               MenuEntrada menu = new MenuEntrada();
               menu.setVisible(true);
               sp.setVisible(false);
               sp.dispose();
           }
           }
           
    }   
       
       catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        
    }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraCarga;
    private javax.swing.JLabel LbLogo;
    private javax.swing.JLabel LbSloganHealtHelp;
    private javax.swing.JLabel LbTituloHealtHelp;
    private javax.swing.JLabel LoadingLable;
    private javax.swing.JLabel LoadingValue;
    private org.edisoncor.gui.panel.Panel PanelAgendarCita;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
