/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.temporal;

/**
 *
 * @author user 123
 */
public class HH_MensajeSuccessfulGeneral extends javax.swing.JDialog {

    /**
     * Creates new form HH_FechaCita
     */
    public HH_MensajeSuccessfulGeneral(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        temporal tm = new temporal();
        TxContraseña.setText(tm.getContraseña());
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCTextField1 = new app.bolivia.swing.JCTextField();
        PanelFechaCita = new org.edisoncor.gui.panel.Panel();
        BnFechaCita = new rojerusan.RSMaterialButtonRectangle();
        LbTituloFechaCita = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LbProfesionalSaludAgendarCita1 = new javax.swing.JLabel();
        LbProfesionalSaludAgendarCita2 = new javax.swing.JLabel();
        TxContraseña = new rojeru_san.RSMPassView();

        jCTextField1.setText("jCTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        PanelFechaCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 190, 166), 5));
        PanelFechaCita.setForeground(new java.awt.Color(1, 122, 91));
        PanelFechaCita.setColorPrimario(new java.awt.Color(255, 255, 255));
        PanelFechaCita.setColorSecundario(new java.awt.Color(255, 255, 255));
        PanelFechaCita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BnFechaCita.setBackground(new java.awt.Color(50, 190, 166));
        BnFechaCita.setText("OK");
        BnFechaCita.setFocusable(false);
        BnFechaCita.setFont(new java.awt.Font("Roboto Medium", 1, 32)); // NOI18N
        BnFechaCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnFechaCitaActionPerformed(evt);
            }
        });
        PanelFechaCita.add(BnFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 80, 70));

        LbTituloFechaCita.setFont(new java.awt.Font("Segoe UI Semibold", 0, 40)); // NOI18N
        LbTituloFechaCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbTituloFechaCita.setText("¡SUCCESSFUL!");
        LbTituloFechaCita.setToolTipText("");
        PanelFechaCita.add(LbTituloFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 380, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Verificado (1).png"))); // NOI18N
        PanelFechaCita.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 140, 130));

        LbProfesionalSaludAgendarCita1.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbProfesionalSaludAgendarCita1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbProfesionalSaludAgendarCita1.setText("Su contraseña ha sido recuperada con éxito.");
        PanelFechaCita.add(LbProfesionalSaludAgendarCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, 20));

        LbProfesionalSaludAgendarCita2.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbProfesionalSaludAgendarCita2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbProfesionalSaludAgendarCita2.setText("Su contraseña es:");
        PanelFechaCita.add(LbProfesionalSaludAgendarCita2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, 20));

        TxContraseña.setForeground(new java.awt.Color(0, 0, 0));
        TxContraseña.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        TxContraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxContraseña.setPlaceholder("Contraseña.");
        PanelFechaCita.add(TxContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 377, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelFechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnFechaCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnFechaCitaActionPerformed
        this.dispose();
    }//GEN-LAST:event_BnFechaCitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HH_MensajeSuccessfulGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HH_MensajeSuccessfulGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HH_MensajeSuccessfulGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HH_MensajeSuccessfulGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HH_MensajeSuccessfulGeneral dialog = new HH_MensajeSuccessfulGeneral(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle BnFechaCita;
    private javax.swing.JLabel LbProfesionalSaludAgendarCita1;
    private javax.swing.JLabel LbProfesionalSaludAgendarCita2;
    private javax.swing.JLabel LbTituloFechaCita;
    private org.edisoncor.gui.panel.Panel PanelFechaCita;
    public static rojeru_san.RSMPassView TxContraseña;
    private app.bolivia.swing.JCTextField jCTextField1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
