/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.SqlOpiniones;
import Clases.SqlRegistroMedico;
import Clases.temporal;
import java.awt.Color;

/**
 *
 * @author EXITO SIMON BOLIVAR
 */
public class HH_PerfilMédico extends javax.swing.JFrame {

    /**
     * Creates new form HH_PerfilMédico
     */
    public HH_PerfilMédico() {
        initComponents();
        this.setLocationRelativeTo(null);
        temporal tm = new temporal();
        SqlRegistroMedico.listarNombreMedico(tm.getID());
        SqlOpiniones.opinionesPacientesMedico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        PanelPerfilMedico = new org.edisoncor.gui.panel.Panel();
        jSeparator1 = new javax.swing.JSeparator();
        LbImagenAppHealtHelp = new javax.swing.JLabel();
        LbHealtHelp = new javax.swing.JLabel();
        LbSloganHealtHelp = new javax.swing.JLabel();
        LbImagenValoraciónMedico = new javax.swing.JLabel();
        Panel2SobreElOpiniones = new org.edisoncor.gui.panel.Panel();
        jLabel17 = new javax.swing.JLabel();
        LbSobreEl1 = new javax.swing.JLabel();
        LbSobreEl2 = new javax.swing.JLabel();
        LbSobreEl3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        LbSobreEl5 = new javax.swing.JLabel();
        LbSobreEl6 = new javax.swing.JLabel();
        LbNombreMedico = new javax.swing.JLabel();
        BnObservarCitasPerfilMedico = new javax.swing.JButton();
        LbProfesionMedico = new javax.swing.JLabel();
        LbNombreDoctorInterfaz = new javax.swing.JLabel();
        LbImagenDoctor = new javax.swing.JLabel();
        LbEditarPerfil = new javax.swing.JLabel();
        LbCerrarSesión = new javax.swing.JLabel();
        Panel3Opiniones = new org.edisoncor.gui.panel.Panel();
        jLabel12 = new javax.swing.JLabel();
        LbOpiniones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbOpinionesMédico = new RSMaterialComponent.RSTableMetroCustom();
        LbImagenDoctor2 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rosendo Bocoro");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPerfilMedico.setColorPrimario(new java.awt.Color(0, 102, 153));
        PanelPerfilMedico.setColorSecundario(new java.awt.Color(0, 153, 102));
        PanelPerfilMedico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelPerfilMedico.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 189, -1, -1));

        LbImagenAppHealtHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal.jpg"))); // NOI18N
        PanelPerfilMedico.add(LbImagenAppHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        LbHealtHelp.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        LbHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbHealtHelp.setText("HealtHelp");
        PanelPerfilMedico.add(LbHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        LbSloganHealtHelp.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        LbSloganHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbSloganHealtHelp.setText("Tu salud en nuestras manos ");
        PanelPerfilMedico.add(LbSloganHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 15));

        LbImagenValoraciónMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EstrellasValoracion.png"))); // NOI18N
        PanelPerfilMedico.add(LbImagenValoraciónMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        Panel2SobreElOpiniones.setBackground(new java.awt.Color(1, 122, 91));
        Panel2SobreElOpiniones.setBorder(new org.edisoncor.gui.util.DropShadowBorder());
        Panel2SobreElOpiniones.setColorPrimario(new java.awt.Color(0, 105, 78));
        Panel2SobreElOpiniones.setColorSecundario(new java.awt.Color(0, 105, 78));
        Panel2SobreElOpiniones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Sitka Banner", 1, 28)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(209, 219, 228));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Sobre él");
        Panel2SobreElOpiniones.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 260, -1));

        LbSobreEl1.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        LbSobreEl1.setForeground(new java.awt.Color(209, 227, 229));
        LbSobreEl1.setText("Soy un especialista en cardiología, poseo un postgrado y");
        Panel2SobreElOpiniones.add(LbSobreEl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        LbSobreEl2.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        LbSobreEl2.setForeground(new java.awt.Color(209, 227, 229));
        LbSobreEl2.setText("calificado con excelencia en el curso de mi doctorado.");
        Panel2SobreElOpiniones.add(LbSobreEl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        LbSobreEl3.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        LbSobreEl3.setForeground(new java.awt.Color(209, 227, 229));
        LbSobreEl3.setText("Mis estudios fueron enfocados en la prestigiosa universidad");
        Panel2SobreElOpiniones.add(LbSobreEl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel22.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(209, 227, 229));
        jLabel22.setText("univalle.");
        Panel2SobreElOpiniones.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        LbSobreEl5.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        LbSobreEl5.setForeground(new java.awt.Color(209, 227, 229));
        LbSobreEl5.setText("Soy una persona dedicada a mi trabajo, mi prioridad es la ");
        Panel2SobreElOpiniones.add(LbSobreEl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        LbSobreEl6.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        LbSobreEl6.setForeground(new java.awt.Color(209, 227, 229));
        LbSobreEl6.setText("vida y salud de mis pacientes...");
        Panel2SobreElOpiniones.add(LbSobreEl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        PanelPerfilMedico.add(Panel2SobreElOpiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 450, 230));

        LbNombreMedico.setFont(new java.awt.Font("Sitka Banner", 1, 28)); // NOI18N
        LbNombreMedico.setForeground(new java.awt.Color(209, 219, 228));
        LbNombreMedico.setText("Dr. Armando Mendoza");
        PanelPerfilMedico.add(LbNombreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 310, -1));

        BnObservarCitasPerfilMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotónObservarCita.png"))); // NOI18N
        BnObservarCitasPerfilMedico.setBorder(null);
        BnObservarCitasPerfilMedico.setBorderPainted(false);
        BnObservarCitasPerfilMedico.setContentAreaFilled(false);
        BnObservarCitasPerfilMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BnObservarCitasPerfilMedico.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotónObservarCita_ON.png"))); // NOI18N
        BnObservarCitasPerfilMedico.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotónObservarCita_ON.png"))); // NOI18N
        BnObservarCitasPerfilMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnObservarCitasPerfilMedicoActionPerformed(evt);
            }
        });
        PanelPerfilMedico.add(BnObservarCitasPerfilMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 280, 90));

        LbProfesionMedico.setFont(new java.awt.Font("Sitka Banner", 0, 16)); // NOI18N
        LbProfesionMedico.setForeground(new java.awt.Color(199, 226, 221));
        LbProfesionMedico.setText("Especialista en cardiología");
        PanelPerfilMedico.add(LbProfesionMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 280, -1));

        LbNombreDoctorInterfaz.setFont(new java.awt.Font("Sitka Banner", 1, 22)); // NOI18N
        LbNombreDoctorInterfaz.setForeground(new java.awt.Color(255, 255, 255));
        LbNombreDoctorInterfaz.setText("Dr. Armando Mendoza");
        PanelPerfilMedico.add(LbNombreDoctorInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 220, 40));

        LbImagenDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbImagenDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Foto usuario.png"))); // NOI18N
        PanelPerfilMedico.add(LbImagenDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 40, 40));

        LbEditarPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-pequeño.png"))); // NOI18N
        LbEditarPerfil.setToolTipText("EDITAR PERFIL");
        LbEditarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbEditarPerfilMouseClicked(evt);
            }
        });
        PanelPerfilMedico.add(LbEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 40, 40));

        LbCerrarSesión.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCerrarSesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion-pequeño.png"))); // NOI18N
        LbCerrarSesión.setToolTipText("CERRAR SESIÓN");
        LbCerrarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbCerrarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCerrarSesiónMouseClicked(evt);
            }
        });
        PanelPerfilMedico.add(LbCerrarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 40, 40));

        Panel3Opiniones.setBorder(new org.edisoncor.gui.util.DropShadowBorder());
        Panel3Opiniones.setColorPrimario(new java.awt.Color(1, 122, 91));
        Panel3Opiniones.setColorSecundario(new java.awt.Color(1, 122, 91));
        Panel3Opiniones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Foto usuario.png"))); // NOI18N
        Panel3Opiniones.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 40, 40));

        LbOpiniones.setFont(new java.awt.Font("Sitka Banner", 1, 28)); // NOI18N
        LbOpiniones.setForeground(new java.awt.Color(209, 219, 228));
        LbOpiniones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbOpiniones.setText("Opiniones de pacientes");
        Panel3Opiniones.add(LbOpiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, -1));

        TbOpinionesMédico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Opinión"
            }
        ));
        TbOpinionesMédico.setBackgoundHead(new java.awt.Color(255, 255, 255));
        TbOpinionesMédico.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        TbOpinionesMédico.setColorSecondary(new java.awt.Color(255, 255, 255));
        TbOpinionesMédico.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        TbOpinionesMédico.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TbOpinionesMédico.setFontRowHover(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TbOpinionesMédico.setFontRowSelect(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TbOpinionesMédico.setForegroundHead(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(TbOpinionesMédico);

        Panel3Opiniones.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 360, 290));

        PanelPerfilMedico.add(Panel3Opiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 380, 360));
        PanelPerfilMedico.add(LbImagenDoctor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 150));

        getContentPane().add(PanelPerfilMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LbEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbEditarPerfilMouseClicked
        HH_EditarPerfilMedico editar = new HH_EditarPerfilMedico();
        editar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbEditarPerfilMouseClicked

    private void LbCerrarSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCerrarSesiónMouseClicked
        MenuEntrada menu = new MenuEntrada();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbCerrarSesiónMouseClicked

    private void BnObservarCitasPerfilMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnObservarCitasPerfilMedicoActionPerformed

        HH_TablaCitasMedico citas = new HH_TablaCitasMedico();
        citas.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BnObservarCitasPerfilMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HH_PerfilMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HH_PerfilMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HH_PerfilMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HH_PerfilMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HH_PerfilMédico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnObservarCitasPerfilMedico;
    private javax.swing.JLabel LbCerrarSesión;
    private javax.swing.JLabel LbEditarPerfil;
    private javax.swing.JLabel LbHealtHelp;
    private javax.swing.JLabel LbImagenAppHealtHelp;
    public static javax.swing.JLabel LbImagenDoctor;
    public static javax.swing.JLabel LbImagenDoctor2;
    private javax.swing.JLabel LbImagenValoraciónMedico;
    public static javax.swing.JLabel LbNombreDoctorInterfaz;
    public static javax.swing.JLabel LbNombreMedico;
    private javax.swing.JLabel LbOpiniones;
    public static javax.swing.JLabel LbProfesionMedico;
    private javax.swing.JLabel LbSloganHealtHelp;
    private javax.swing.JLabel LbSobreEl1;
    private javax.swing.JLabel LbSobreEl2;
    private javax.swing.JLabel LbSobreEl3;
    private javax.swing.JLabel LbSobreEl5;
    private javax.swing.JLabel LbSobreEl6;
    private org.edisoncor.gui.panel.Panel Panel2SobreElOpiniones;
    private org.edisoncor.gui.panel.Panel Panel3Opiniones;
    private org.edisoncor.gui.panel.Panel PanelPerfilMedico;
    public static RSMaterialComponent.RSTableMetroCustom TbOpinionesMédico;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
