/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.SqlListarCitaMedico;
import Clases.SqlRegistroMedico;
import Clases.SqlRegistroPaciente;
import Clases.temporal;
import javax.swing.JOptionPane;

/**
 *
 * @author EXITO SIMON BOLIVAR
 */
public class HH_SoyMédico extends javax.swing.JFrame {

    /**
     * Creates new form HH_SoyMédico
     */
    public HH_SoyMédico() {
        initComponents();
        SqlRegistroMedico.listarMedicos();
        temporal tm = new temporal();
        SqlRegistroPaciente.ListarNombrePacienteSoyMedico(tm.getID());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSoyMedico = new org.edisoncor.gui.panel.Panel();
        jSeparator2 = new javax.swing.JSeparator();
        LbImagenAppHealtHelp = new javax.swing.JLabel();
        LbHealtHelp = new javax.swing.JLabel();
        LbSloganHealtHelp = new javax.swing.JLabel();
        LbSoyMedico1 = new javax.swing.JLabel();
        LbSoyMedico2 = new javax.swing.JLabel();
        LbSoyMedico3 = new javax.swing.JLabel();
        LbSoyMedico4 = new javax.swing.JLabel();
        BnVolverSoyMedico = new javax.swing.JButton();
        LbImagenUsuario = new javax.swing.JLabel();
        LbNombrePacienteInterfaz = new javax.swing.JLabel();
        LbCitasAgendadas = new javax.swing.JLabel();
        LbEditarPerfil = new javax.swing.JLabel();
        LbCerrarSesión = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbListarMedicos = new RSMaterialComponent.RSTableMetroCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSoyMedico.setColorPrimario(new java.awt.Color(0, 102, 153));
        PanelSoyMedico.setColorSecundario(new java.awt.Color(0, 153, 102));
        PanelSoyMedico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelSoyMedico.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 189, -1, -1));

        LbImagenAppHealtHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal.jpg"))); // NOI18N
        LbImagenAppHealtHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbImagenAppHealtHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbImagenAppHealtHelpMouseClicked(evt);
            }
        });
        PanelSoyMedico.add(LbImagenAppHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        LbHealtHelp.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        LbHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbHealtHelp.setText("HealtHelp");
        PanelSoyMedico.add(LbHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        LbSloganHealtHelp.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        LbSloganHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbSloganHealtHelp.setText("Tu salud en nuestras manos ");
        PanelSoyMedico.add(LbSloganHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 15));

        LbSoyMedico1.setFont(new java.awt.Font("Sitka Banner", 0, 20)); // NOI18N
        LbSoyMedico1.setForeground(new java.awt.Color(199, 226, 221));
        LbSoyMedico1.setText("Bienvenido a la pestaña");
        LbSoyMedico1.setToolTipText("");
        PanelSoyMedico.add(LbSoyMedico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 190, 20));

        LbSoyMedico2.setFont(new java.awt.Font("Segoe Script", 0, 16)); // NOI18N
        LbSoyMedico2.setForeground(new java.awt.Color(199, 226, 221));
        LbSoyMedico2.setText("\"Soy Médico\"");
        PanelSoyMedico.add(LbSoyMedico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 120, 40));

        LbSoyMedico3.setFont(new java.awt.Font("Sitka Banner", 0, 20)); // NOI18N
        LbSoyMedico3.setForeground(new java.awt.Color(199, 226, 221));
        LbSoyMedico3.setText("Aquí podrás ver todos los perfiles registrados y recomendados de los profesionales de la salud,");
        PanelSoyMedico.add(LbSoyMedico3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 730, 20));

        LbSoyMedico4.setFont(new java.awt.Font("Sitka Banner", 0, 20)); // NOI18N
        LbSoyMedico4.setForeground(new java.awt.Color(199, 226, 221));
        LbSoyMedico4.setText("quienes brindan sus servicios de forma particular.");
        PanelSoyMedico.add(LbSoyMedico4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 20));

        BnVolverSoyMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonVolver.png"))); // NOI18N
        BnVolverSoyMedico.setBorder(null);
        BnVolverSoyMedico.setBorderPainted(false);
        BnVolverSoyMedico.setContentAreaFilled(false);
        BnVolverSoyMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BnVolverSoyMedico.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonVolver2 .png"))); // NOI18N
        BnVolverSoyMedico.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonVolver2 .png"))); // NOI18N
        BnVolverSoyMedico.setSelected(true);
        BnVolverSoyMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnVolverSoyMedicoActionPerformed(evt);
            }
        });
        PanelSoyMedico.add(BnVolverSoyMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 210, 70));

        LbImagenUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Foto usuario.png"))); // NOI18N
        PanelSoyMedico.add(LbImagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 40, 40));

        LbNombrePacienteInterfaz.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbNombrePacienteInterfaz.setForeground(new java.awt.Color(255, 255, 255));
        LbNombrePacienteInterfaz.setText("Rosendo Bucuru");
        PanelSoyMedico.add(LbNombrePacienteInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 180, 40));

        LbCitasAgendadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCitasAgendadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.png"))); // NOI18N
        LbCitasAgendadas.setToolTipText("CITAS AGENDADAS");
        LbCitasAgendadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbCitasAgendadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCitasAgendadasMouseClicked(evt);
            }
        });
        PanelSoyMedico.add(LbCitasAgendadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 40, 40));

        LbEditarPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-pequeño.png"))); // NOI18N
        LbEditarPerfil.setToolTipText("EDITAR PERFIL");
        LbEditarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbEditarPerfilMouseClicked(evt);
            }
        });
        PanelSoyMedico.add(LbEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 40, 40));

        LbCerrarSesión.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCerrarSesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion-pequeño.png"))); // NOI18N
        LbCerrarSesión.setToolTipText("CERRAR SESIÓN");
        LbCerrarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbCerrarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCerrarSesiónMouseClicked(evt);
            }
        });
        PanelSoyMedico.add(LbCerrarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 40, 40));

        TbListarMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Especialidad", "Correo"
            }
        ));
        TbListarMedicos.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        TbListarMedicos.setColorSecundaryText(new java.awt.Color(0, 0, 255));
        TbListarMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbListarMedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbListarMedicos);

        PanelSoyMedico.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 850, 300));

        getContentPane().add(PanelSoyMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnVolverSoyMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnVolverSoyMedicoActionPerformed
     
        HhAgendarCita agendarcita = new HhAgendarCita();
        agendarcita.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BnVolverSoyMedicoActionPerformed

    private void LbCitasAgendadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCitasAgendadasMouseClicked

        HH_TablaCitasPaciente citasAgendadas = new HH_TablaCitasPaciente();
        citasAgendadas.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbCitasAgendadasMouseClicked

    private void LbEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbEditarPerfilMouseClicked

        HH_Cambios editarperfilpaciente = new HH_Cambios();
        editarperfilpaciente.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_LbEditarPerfilMouseClicked

    private void LbCerrarSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCerrarSesiónMouseClicked

        MenuEntrada menu = new MenuEntrada();
        menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbCerrarSesiónMouseClicked

    private void LbImagenAppHealtHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbImagenAppHealtHelpMouseClicked
    
        HhAgendarCita principal = new HhAgendarCita();
        principal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_LbImagenAppHealtHelpMouseClicked

    private void TbListarMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbListarMedicosMouseClicked
        
        int seleccion = TbListarMedicos.getSelectedRow();

        temporal variable = new temporal();
        variable.setCorreoMedicoSeleccionado(String.valueOf(TbListarMedicos.getValueAt(seleccion, 3)));
        HhOpiniones opiniones = new HhOpiniones();
        opiniones.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_TbListarMedicosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HH_SoyMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HH_SoyMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HH_SoyMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HH_SoyMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HH_SoyMédico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnVolverSoyMedico;
    private javax.swing.JLabel LbCerrarSesión;
    private javax.swing.JLabel LbCitasAgendadas;
    private javax.swing.JLabel LbEditarPerfil;
    private javax.swing.JLabel LbHealtHelp;
    private javax.swing.JLabel LbImagenAppHealtHelp;
    public static javax.swing.JLabel LbImagenUsuario;
    public static javax.swing.JLabel LbNombrePacienteInterfaz;
    private javax.swing.JLabel LbSloganHealtHelp;
    private javax.swing.JLabel LbSoyMedico1;
    private javax.swing.JLabel LbSoyMedico2;
    private javax.swing.JLabel LbSoyMedico3;
    private javax.swing.JLabel LbSoyMedico4;
    private org.edisoncor.gui.panel.Panel PanelSoyMedico;
    public static RSMaterialComponent.RSTableMetroCustom TbListarMedicos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
