/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.SqlActualizarDatosPaciente;
import Clases.SqlAgendarCita;
import Clases.SqlRegistroPaciente;
import Clases.temporal;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class HhAgendarCita extends javax.swing.JFrame {

    public static String especialidad;

    /**
     * Creates new form HhAgendarCita
     */
    public HhAgendarCita() {
        initComponents();
        this.setLocationRelativeTo(null);
        temporal tm = new temporal();
        SqlRegistroPaciente.ListarNombrePaciente(tm.getID());
    }

    public static int DiaActual;
    public static int MesActual;
    public static int AnioActual;
    public static int DiaSeleccionado;
    public static int MesSeleccionado;
    public static int AnioSeleccionado;

    private String VerificacionFecha(String fecha) {
        String Verificar = "";
        if(fecha.equals("")){
            
        }
        else{
            // Obtener Fecha actual
        SimpleDateFormat dia = new SimpleDateFormat("dd");
        SimpleDateFormat mes = new SimpleDateFormat("MM");
        SimpleDateFormat Anio = new SimpleDateFormat("yyyy");
        java.util.Date FechaActual = new java.util.Date();
        DiaActual = Integer.parseInt(String.valueOf(dia.format(FechaActual)));
        MesActual = Integer.parseInt(String.valueOf(mes.format(FechaActual)));
        AnioActual = Integer.parseInt(String.valueOf(Anio.format(FechaActual)));

        //Obtener fecha seleccionada
        java.util.Date fechaSeleccionada = HhAgendarCita.RsCalendarDisponibilidad.getDatoFecha();
        SimpleDateFormat formatoDia = new SimpleDateFormat("dd");
        SimpleDateFormat formatoMes = new SimpleDateFormat("MM");
        SimpleDateFormat formatoAnio = new SimpleDateFormat("yyyy");

        DiaSeleccionado = Integer.parseInt(String.valueOf(formatoDia.format(fechaSeleccionada)));
        //JOptionPane.showMessageDialog(null, DiaSeleccionado);
        MesSeleccionado = Integer.parseInt(String.valueOf(formatoMes.format(fechaSeleccionada)));
        //JOptionPane.showMessageDialog(null, MesSeleccionado);
        AnioSeleccionado = Integer.parseInt(String.valueOf(formatoAnio.format(fechaSeleccionada)));
        //JOptionPane.showMessageDialog(null, AnioSeleccionado);
        //Condicional para escoger fecha Mayores
        
        if (AnioActual <= AnioSeleccionado) {
            if (MesActual <= MesSeleccionado) {
                if (DiaActual <= DiaSeleccionado) {

                    JOptionPane.showMessageDialog(null, "Fecha correcta");
                    Verificar = "Fecha correcta";

                } else {
                    JOptionPane.showMessageDialog(null, "Fecha incorrecta");
                    RsCalendarDisponibilidad.setDatoFecha(null);
                    Verificar = "Fecha incorrecta";
                }
            } else {
                JOptionPane.showMessageDialog(null, "Fecha incorrecta");
                RsCalendarDisponibilidad.setDatoFecha(null);
                Verificar = "Fecha incorrecta";
            }
        } else {
            JOptionPane.showMessageDialog(null, "Fecha incorrecta");
            RsCalendarDisponibilidad.setDatoFecha(null);
            Verificar = "Fecha incorrecta";

        }                        
        }    
        
        return Verificar;
    }
    

    private void limpiarCampos() {
        this.TxProfesionalSaludAgendarCita.setText("");
        this.RsCalendarDisponibilidad.setDatoFecha(null);
        this.TxHoraProbar.setText("");
        this.CbxTipoProblemaAgendarCita.setSelectedIndex(0);
        this.TxaDescripcionProblemaAgendarCita.setText("");

    }

    public static String genero;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelAgendarCita = new org.edisoncor.gui.panel.Panel();
        jSeparator1 = new javax.swing.JSeparator();
        LbLogoAppHealtHelp = new javax.swing.JLabel();
        LbSloganHealtHelp = new javax.swing.JLabel();
        LbSubtituloAgendarCita = new RSMaterialComponent.RSLabelTextIcon();
        LbGeneroAgendarCita = new javax.swing.JLabel();
        DescripciónDetalladaProblemaAgendarCita = new javax.swing.JLabel();
        LbDisponibilidadAgendarCita = new javax.swing.JLabel();
        CbxTipoProblemaAgendarCita = new RSMaterialComponent.RSComboBox();
        LbHoraAgendarCita = new javax.swing.JLabel();
        RbnOtroAgendarCita = new javax.swing.JRadioButton();
        RbnMasculinoAgendarCita = new javax.swing.JRadioButton();
        RbnFemeninoAgendarCita = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        LbProfesionalSaludAgendarCita = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxaDescripcionProblemaAgendarCita = new javax.swing.JTextArea();
        LbTipoProblemaAgendarCita = new javax.swing.JLabel();
        BnAgendarCita = new javax.swing.JButton();
        BnSoyMedico = new javax.swing.JButton();
        LbTituloHealtHelp = new javax.swing.JLabel();
        LbNombrePacienteInterfaz = new javax.swing.JLabel();
        LbImagenUsuario = new javax.swing.JLabel();
        LbCerrarSesión = new javax.swing.JLabel();
        LbEditarPerfil = new javax.swing.JLabel();
        RsCalendarDisponibilidad = new rojeru_san.componentes.RSDateChooser();
        TxProfesionalSaludAgendarCita = new necesario.TextField();
        LbCitasAgendadas = new javax.swing.JLabel();
        TxHoraProbar = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        PanelAgendarCita.setColorPrimario(new java.awt.Color(0, 102, 153));
        PanelAgendarCita.setColorSecundario(new java.awt.Color(0, 153, 102));
        PanelAgendarCita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelAgendarCita.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 189, -1, -1));

        LbLogoAppHealtHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal.jpg"))); // NOI18N
        LbLogoAppHealtHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LbLogoAppHealtHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbLogoAppHealtHelpMouseClicked(evt);
            }
        });
        PanelAgendarCita.add(LbLogoAppHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        LbSloganHealtHelp.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        LbSloganHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbSloganHealtHelp.setText("Tu salud en nuestras manos ");
        PanelAgendarCita.add(LbSloganHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 15));

        LbSubtituloAgendarCita.setForeground(new java.awt.Color(6, 52, 86));
        LbSubtituloAgendarCita.setText("Agendar una cita");
        LbSubtituloAgendarCita.setFont(new java.awt.Font("Sitka Banner", 1, 32)); // NOI18N
        LbSubtituloAgendarCita.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DATE_RANGE);
        PanelAgendarCita.add(LbSubtituloAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 290, -1));

        LbGeneroAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbGeneroAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbGeneroAgendarCita.setText("Género");
        PanelAgendarCita.add(LbGeneroAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 220, -1));

        DescripciónDetalladaProblemaAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        DescripciónDetalladaProblemaAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        DescripciónDetalladaProblemaAgendarCita.setText("Descripción detallada del problema");
        PanelAgendarCita.add(DescripciónDetalladaProblemaAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 260, -1));

        LbDisponibilidadAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbDisponibilidadAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbDisponibilidadAgendarCita.setText("Disponibilidad");
        PanelAgendarCita.add(LbDisponibilidadAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 220, -1));

        CbxTipoProblemaAgendarCita.setForeground(new java.awt.Color(0, 0, 0));
        CbxTipoProblemaAgendarCita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar...", "General", "Neuronal", "Pulmonar", "Cardioba", "Urgente", "Otro" }));
        CbxTipoProblemaAgendarCita.setColorArrow(new java.awt.Color(0, 0, 0));
        CbxTipoProblemaAgendarCita.setColorBoton(new java.awt.Color(255, 255, 255));
        CbxTipoProblemaAgendarCita.setColorDisabledIndex(new java.awt.Color(255, 255, 255));
        CbxTipoProblemaAgendarCita.setColorFondo(new java.awt.Color(255, 255, 255));
        CbxTipoProblemaAgendarCita.setColorSeleccion(new java.awt.Color(0, 102, 204));
        CbxTipoProblemaAgendarCita.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PanelAgendarCita.add(CbxTipoProblemaAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 260, 35));

        LbHoraAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbHoraAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbHoraAgendarCita.setText("Hora (formato 24h)");
        PanelAgendarCita.add(LbHoraAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 220, -1));

        RbnOtroAgendarCita.setBackground(new java.awt.Color(0, 146, 108));
        buttonGroup1.add(RbnOtroAgendarCita);
        RbnOtroAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        RbnOtroAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        RbnOtroAgendarCita.setText("Otro");
        RbnOtroAgendarCita.setBorder(null);
        PanelAgendarCita.add(RbnOtroAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 60, 30));

        RbnMasculinoAgendarCita.setBackground(new java.awt.Color(0, 146, 108));
        buttonGroup1.add(RbnMasculinoAgendarCita);
        RbnMasculinoAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        RbnMasculinoAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        RbnMasculinoAgendarCita.setText("Masculino");
        RbnMasculinoAgendarCita.setBorder(null);
        PanelAgendarCita.add(RbnMasculinoAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 100, 30));

        RbnFemeninoAgendarCita.setBackground(new java.awt.Color(0, 146, 108));
        buttonGroup1.add(RbnFemeninoAgendarCita);
        RbnFemeninoAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        RbnFemeninoAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        RbnFemeninoAgendarCita.setText("Femenino");
        RbnFemeninoAgendarCita.setBorder(null);
        PanelAgendarCita.add(RbnFemeninoAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 90, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        PanelAgendarCita.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 30, 270));

        LbProfesionalSaludAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbProfesionalSaludAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbProfesionalSaludAgendarCita.setText("Profesional de la salud");
        PanelAgendarCita.add(LbProfesionalSaludAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 220, -1));

        TxaDescripcionProblemaAgendarCita.setColumns(20);
        TxaDescripcionProblemaAgendarCita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxaDescripcionProblemaAgendarCita.setRows(5);
        TxaDescripcionProblemaAgendarCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane1.setViewportView(TxaDescripcionProblemaAgendarCita);

        PanelAgendarCita.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 280, 140));

        LbTipoProblemaAgendarCita.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        LbTipoProblemaAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        LbTipoProblemaAgendarCita.setText("Especialidad (tipo de problema)");
        PanelAgendarCita.add(LbTipoProblemaAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 220, -1));

        BnAgendarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonAgendar.png"))); // NOI18N
        BnAgendarCita.setBorder(null);
        BnAgendarCita.setBorderPainted(false);
        BnAgendarCita.setContentAreaFilled(false);
        BnAgendarCita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BnAgendarCita.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonAgendar_ON.png"))); // NOI18N
        BnAgendarCita.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonAgendar_ON.png"))); // NOI18N
        BnAgendarCita.setSelected(true);
        BnAgendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnAgendarCitaActionPerformed(evt);
            }
        });
        PanelAgendarCita.add(BnAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 150, 60));

        BnSoyMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botón soy medico.png"))); // NOI18N
        BnSoyMedico.setBorder(null);
        BnSoyMedico.setBorderPainted(false);
        BnSoyMedico.setContentAreaFilled(false);
        BnSoyMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BnSoyMedico.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botón soy medico_ON.png"))); // NOI18N
        BnSoyMedico.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botón soy medico_ON.png"))); // NOI18N
        BnSoyMedico.setSelected(true);
        BnSoyMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnSoyMedicoActionPerformed(evt);
            }
        });
        PanelAgendarCita.add(BnSoyMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 150, 150));

        LbTituloHealtHelp.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        LbTituloHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbTituloHealtHelp.setText("HealtHelp");
        PanelAgendarCita.add(LbTituloHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        LbNombrePacienteInterfaz.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbNombrePacienteInterfaz.setForeground(new java.awt.Color(255, 255, 255));
        LbNombrePacienteInterfaz.setText("Rosendo Bucuru");
        PanelAgendarCita.add(LbNombrePacienteInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 180, 40));

        LbImagenUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Foto usuario.png"))); // NOI18N
        PanelAgendarCita.add(LbImagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 40, 40));

        LbCerrarSesión.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCerrarSesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion-pequeño.png"))); // NOI18N
        LbCerrarSesión.setToolTipText("CERRAR SESIÓN");
        LbCerrarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LbCerrarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCerrarSesiónMouseClicked(evt);
            }
        });
        PanelAgendarCita.add(LbCerrarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 40, 40));

        LbEditarPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-pequeño.png"))); // NOI18N
        LbEditarPerfil.setToolTipText("EDITAR PERFIL");
        LbEditarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LbEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbEditarPerfilMouseClicked(evt);
            }
        });
        PanelAgendarCita.add(LbEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 40, 40));
        PanelAgendarCita.add(RsCalendarDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 260, -1));

        TxProfesionalSaludAgendarCita.setForeground(new java.awt.Color(0, 0, 0));
        TxProfesionalSaludAgendarCita.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxProfesionalSaludAgendarCita.setPlaceholder("Número de identificación doctor...");
        TxProfesionalSaludAgendarCita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxProfesionalSaludAgendarCitaKeyTyped(evt);
            }
        });
        PanelAgendarCita.add(TxProfesionalSaludAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 260, 35));

        LbCitasAgendadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCitasAgendadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.png"))); // NOI18N
        LbCitasAgendadas.setToolTipText("CITAS AGENDADAS");
        LbCitasAgendadas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LbCitasAgendadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCitasAgendadasMouseClicked(evt);
            }
        });
        PanelAgendarCita.add(LbCitasAgendadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 40, 40));

        try {
            TxHoraProbar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxHoraProbar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PanelAgendarCita.add(TxHoraProbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 260, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAgendarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAgendarCita, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnSoyMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnSoyMedicoActionPerformed

        HH_SoyMédico soymedico = new HH_SoyMédico();
        soymedico.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BnSoyMedicoActionPerformed

    private void LbCerrarSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCerrarSesiónMouseClicked

        MenuEntrada menu = new MenuEntrada();
        menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbCerrarSesiónMouseClicked

    private void BnAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnAgendarCitaActionPerformed

        String fecha = RsCalendarDisponibilidad.getDatoFecha().toString();
        String Verificar = VerificacionFecha(fecha);

        if (TxProfesionalSaludAgendarCita.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecciona un profesional de la salud para agendar la cita.");
        } ///////////////////////////////////////////////////////////////////////////////
        else if (fecha.equals("")) {
            HH_MensajeError error = new HH_MensajeError(this, true);
            HH_MensajeError.Lb1.setText("Debes digitar una fecha.");
            HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
            error.setVisible(true);
        } ///////////////////////////////////////////////////////////////////////////////
        else if (Verificar.equals("Fecha incorrecta") || Verificar.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite por favor la fecha");
        } /////////////////////////////////////////////////////////////////////////////
        else if (Validar_Campo_Hora(TxHoraProbar.getText()) == false) {
            JOptionPane.showMessageDialog(null, "La hora digitada es incorrecta");
        } else if (CbxTipoProblemaAgendarCita.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selecciona el tipo de problema que presentas");
        } ///////////////////////////////////////////////////////////////////////////////////
        else if (TxaDescripcionProblemaAgendarCita.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes escribir detalladamente tu problema");
        } /////////////////////////////////////////////////////////////////////////////
        else {

            if (RbnMasculinoAgendarCita.isSelected()) {
                genero = "Masculino";

            } else if (RbnFemeninoAgendarCita.isSelected()) {
                genero = "Femenino";
            } else if (RbnOtroAgendarCita.isSelected()) {
                genero = "otro";
            }

            especialidad = CbxTipoProblemaAgendarCita.getSelectedItem().toString().trim();
            temporal pm = new temporal();

            int opcion = SqlAgendarCita.agendarCita(pm.getID(),pm.getNombre());
            if (opcion > 0) {

                HH_MensajeSuccessful successful = new HH_MensajeSuccessful(this, true);
                successful.setVisible(true);

                limpiarCampos();
            } else {

                HH_MensajeError error = new HH_MensajeError(this, true);
                error.setVisible(true);

                limpiarCampos();
            }
            this.limpiarCampos();

        }

    }//GEN-LAST:event_BnAgendarCitaActionPerformed

    private void LbCitasAgendadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCitasAgendadasMouseClicked

        HH_TablaCitasPaciente citasAgendadas = new HH_TablaCitasPaciente();
        citasAgendadas.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbCitasAgendadasMouseClicked

    private void LbEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbEditarPerfilMouseClicked

        HH_Cambios editarperfilpaciente = new HH_Cambios();
        editarperfilpaciente.setVisible(true);
        this.dispose();
        temporal tm = new temporal();
        SqlActualizarDatosPaciente.buscarDatos(tm.getID());

    }//GEN-LAST:event_LbEditarPerfilMouseClicked

    private void LbLogoAppHealtHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbLogoAppHealtHelpMouseClicked

        HhAgendarCita principal = new HhAgendarCita();
        principal.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbLogoAppHealtHelpMouseClicked

    private void TxProfesionalSaludAgendarCitaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxProfesionalSaludAgendarCitaKeyTyped
        
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        
    }//GEN-LAST:event_TxProfesionalSaludAgendarCitaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HhAgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HhAgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HhAgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HhAgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HhAgendarCita().setVisible(true);
            }
        });
    }

    public Boolean Validar_Campo_Hora(String Hora) {
        boolean b;
        char[] a = Hora.toString().toCharArray();
        String[] c = Hora.split(":");
        if ((a[0] == ' ') || (a[1] == ' ') || (a[2] == ' ') || (a[3] == ' ') || (a[4] == ' ') || (Integer.parseInt(c[0]) > 24) || (Integer.parseInt(c[1]) > 59)) {
            b = false;

        } else {
            b = true;
        }
        return b;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnAgendarCita;
    private javax.swing.JButton BnSoyMedico;
    public static RSMaterialComponent.RSComboBox CbxTipoProblemaAgendarCita;
    private javax.swing.JLabel DescripciónDetalladaProblemaAgendarCita;
    private javax.swing.JLabel LbCerrarSesión;
    private javax.swing.JLabel LbCitasAgendadas;
    private javax.swing.JLabel LbDisponibilidadAgendarCita;
    private javax.swing.JLabel LbEditarPerfil;
    private javax.swing.JLabel LbGeneroAgendarCita;
    private javax.swing.JLabel LbHoraAgendarCita;
    public static javax.swing.JLabel LbImagenUsuario;
    private javax.swing.JLabel LbLogoAppHealtHelp;
    public static javax.swing.JLabel LbNombrePacienteInterfaz;
    private javax.swing.JLabel LbProfesionalSaludAgendarCita;
    private javax.swing.JLabel LbSloganHealtHelp;
    private RSMaterialComponent.RSLabelTextIcon LbSubtituloAgendarCita;
    private javax.swing.JLabel LbTipoProblemaAgendarCita;
    private javax.swing.JLabel LbTituloHealtHelp;
    private org.edisoncor.gui.panel.Panel PanelAgendarCita;
    public static javax.swing.JRadioButton RbnFemeninoAgendarCita;
    public static javax.swing.JRadioButton RbnMasculinoAgendarCita;
    public static javax.swing.JRadioButton RbnOtroAgendarCita;
    public static rojeru_san.componentes.RSDateChooser RsCalendarDisponibilidad;
    public static javax.swing.JFormattedTextField TxHoraProbar;
    public static necesario.TextField TxProfesionalSaludAgendarCita;
    public static javax.swing.JTextArea TxaDescripcionProblemaAgendarCita;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
