/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.SqlRecuperarContraseña;
import Clases.SqlRegistroPaciente;
import Clases.temporal;
import static Vistas.Iniciar_Sesion_HH.TxContraseña;

/**
 *
 * @author David
 */
public class HhOlvidoContraseña extends javax.swing.JFrame {

    /**
     * Creates new form HhOlvidoContraseña
     */
    public HhOlvidoContraseña() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        LbTituloOlvidarContra = new javax.swing.JLabel();
        LbSubtitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LbNumeroDocumentoOlvidadoContraseña = new javax.swing.JLabel();
        LbCorreoElectronicoOlvidadoContraseña = new javax.swing.JLabel();
        TxCorreoElectronicoOlvidadoContraseña = new rojeru_san.RSMTextFull();
        TxNumeroDocumentoOlvidadoContraseña = new rojeru_san.RSMTextFull();
        BnSiguienteOlvidadoContraseña = new rojerusan.RSMaterialButtonRectangle();
        BnSalirOlvidadoContraseña = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panel1.setColorPrimario(new java.awt.Color(0, 102, 153));
        panel1.setColorSecundario(new java.awt.Color(0, 153, 102));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbTituloOlvidarContra.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        LbTituloOlvidarContra.setForeground(new java.awt.Color(255, 255, 255));
        LbTituloOlvidarContra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbTituloOlvidarContra.setText("¿Has olvidado tu contraseña?");
        panel1.add(LbTituloOlvidarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, 412, -1));

        LbSubtitulo.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        LbSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbSubtitulo.setText("¡Te ayudamos a recuperarla!");
        panel1.add(LbSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 64, 286, -1));
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 189, -1, -1));

        LbNumeroDocumentoOlvidadoContraseña.setFont(new java.awt.Font("Algerian", 2, 16)); // NOI18N
        LbNumeroDocumentoOlvidadoContraseña.setForeground(new java.awt.Color(255, 255, 255));
        LbNumeroDocumentoOlvidadoContraseña.setText("Numero de documento");
        panel1.add(LbNumeroDocumentoOlvidadoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 112, 189, -1));

        LbCorreoElectronicoOlvidadoContraseña.setFont(new java.awt.Font("Algerian", 2, 16)); // NOI18N
        LbCorreoElectronicoOlvidadoContraseña.setForeground(new java.awt.Color(255, 255, 255));
        LbCorreoElectronicoOlvidadoContraseña.setText("Correo electrónico");
        panel1.add(LbCorreoElectronicoOlvidadoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 180, -1));

        TxCorreoElectronicoOlvidadoContraseña.setForeground(new java.awt.Color(0, 0, 0));
        TxCorreoElectronicoOlvidadoContraseña.setBordeColorFocus(new java.awt.Color(0, 153, 153));
        TxCorreoElectronicoOlvidadoContraseña.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        TxCorreoElectronicoOlvidadoContraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxCorreoElectronicoOlvidadoContraseña.setPlaceholder("Correo electrónico.");
        panel1.add(TxCorreoElectronicoOlvidadoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 320, 32));

        TxNumeroDocumentoOlvidadoContraseña.setForeground(new java.awt.Color(0, 0, 0));
        TxNumeroDocumentoOlvidadoContraseña.setBordeColorFocus(new java.awt.Color(0, 153, 153));
        TxNumeroDocumentoOlvidadoContraseña.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        TxNumeroDocumentoOlvidadoContraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxNumeroDocumentoOlvidadoContraseña.setPlaceholder("Número de documento.");
        panel1.add(TxNumeroDocumentoOlvidadoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 320, 32));

        BnSiguienteOlvidadoContraseña.setBackground(new java.awt.Color(255, 255, 255));
        BnSiguienteOlvidadoContraseña.setForeground(new java.awt.Color(0, 0, 0));
        BnSiguienteOlvidadoContraseña.setText("Login");
        BnSiguienteOlvidadoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnSiguienteOlvidadoContraseñaActionPerformed(evt);
            }
        });
        panel1.add(BnSiguienteOlvidadoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 120, 50));

        BnSalirOlvidadoContraseña.setBackground(new java.awt.Color(255, 255, 255));
        BnSalirOlvidadoContraseña.setForeground(new java.awt.Color(0, 0, 0));
        BnSalirOlvidadoContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Out.png"))); // NOI18N
        BnSalirOlvidadoContraseña.setText("Salir");
        BnSalirOlvidadoContraseña.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BnSalirOlvidadoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnSalirOlvidadoContraseñaActionPerformed(evt);
            }
        });
        panel1.add(BnSalirOlvidadoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnSalirOlvidadoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnSalirOlvidadoContraseñaActionPerformed
    
        MenuEntrada menuentrada = new MenuEntrada();
        menuentrada.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BnSalirOlvidadoContraseñaActionPerformed

    private void BnSiguienteOlvidadoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnSiguienteOlvidadoContraseñaActionPerformed
        
        String DocumentoIdentidad = TxNumeroDocumentoOlvidadoContraseña.getText();
        String busqueda_Usuario = SqlRecuperarContraseña.buscarUsuarioRegistrado(TxNumeroDocumentoOlvidadoContraseña.getText(), TxCorreoElectronicoOlvidadoContraseña.getText());

        if (busqueda_Usuario.equals("Usuario encontrado")) {
            String buscarContraseñaUsuario = SqlRecuperarContraseña.buscarContraseñaUsuario(TxNumeroDocumentoOlvidadoContraseña.getText());
            temporal tm = new temporal();
            tm.setContraseña(buscarContraseñaUsuario);
            HH_MensajeSuccessfulGeneral recuperadoContra = new HH_MensajeSuccessfulGeneral(this, true);
            recuperadoContra.setVisible(true);
        } else {
            HH_MensajeErrorGeneral error = new HH_MensajeErrorGeneral(this, true);
            error.setVisible(true);
        }
        
    }//GEN-LAST:event_BnSiguienteOlvidadoContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HhOlvidoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HhOlvidoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HhOlvidoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HhOlvidoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HhOlvidoContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle BnSalirOlvidadoContraseña;
    private rojerusan.RSMaterialButtonRectangle BnSiguienteOlvidadoContraseña;
    private javax.swing.JLabel LbCorreoElectronicoOlvidadoContraseña;
    private javax.swing.JLabel LbNumeroDocumentoOlvidadoContraseña;
    private javax.swing.JLabel LbSubtitulo;
    private javax.swing.JLabel LbTituloOlvidarContra;
    public static rojeru_san.RSMTextFull TxCorreoElectronicoOlvidadoContraseña;
    public static rojeru_san.RSMTextFull TxNumeroDocumentoOlvidadoContraseña;
    private javax.swing.JSeparator jSeparator1;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
