/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.SqlOpiniones;
import Clases.SqlRegistroMedico;
import Clases.SqlRegistroPaciente;
import Clases.temporal;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class HhOpiniones extends javax.swing.JFrame {

    /**
     * Creates new form HhOpiniones
     */
    public HhOpiniones() {
        initComponents();
        this.setLocationRelativeTo(null);
        temporal tm = new temporal();
        SqlRegistroMedico.listarDatosMedico(tm.getCorreoMedicoSeleccionado());
        SqlRegistroPaciente.ListarNombrePacienteOpiniones(tm.getID());
        SqlOpiniones.listarOpiniones(tm.getCorreoMedicoSeleccionado());
    }
    
    private void limpiarCampos() {
        
        this.TxAgregaComentarioOpiniones.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        LbImagenAppHealtHelp = new javax.swing.JLabel();
        LbHealtHelp = new javax.swing.JLabel();
        LbSloganHealtHelp = new javax.swing.JLabel();
        LbEspecialidadDoctor = new javax.swing.JLabel();
        LbImagenDoctorPerfil = new javax.swing.JLabel();
        LbImagenCalificacionDoctor = new javax.swing.JLabel();
        LbNombreDoctorPerfil = new javax.swing.JLabel();
        BnReservarCitaOpiniones = new javax.swing.JButton();
        Panel3Opiniones = new org.edisoncor.gui.panel.Panel();
        TxAgregaComentarioOpiniones = new RSMaterialComponent.RSTextFieldOne();
        jLabel12 = new javax.swing.JLabel();
        LbOpiniones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbOpiniones = new RSMaterialComponent.RSTableMetroCustom();
        BnEnviar = new rojeru_san.RSButton();
        BnVolverOpiniones = new javax.swing.JButton();
        LbNombrePacienteInterfaz3 = new javax.swing.JLabel();
        LbImagenUsuario = new javax.swing.JLabel();
        LbCitasAgendadas = new javax.swing.JLabel();
        LbEditarPerfil = new javax.swing.JLabel();
        LbCerrarSesión = new javax.swing.JLabel();
        Panel2SobreElOpiniones = new org.edisoncor.gui.panel.Panel();
        jLabel17 = new javax.swing.JLabel();
        LbSobreEl1 = new javax.swing.JLabel();
        LbSobreEl2 = new javax.swing.JLabel();
        LbSobreEl3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        LbSobreEl5 = new javax.swing.JLabel();
        LbSobreEl6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setColorPrimario(new java.awt.Color(0, 102, 153));
        panel1.setColorSecundario(new java.awt.Color(0, 153, 102));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbImagenAppHealtHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal.jpg"))); // NOI18N
        LbImagenAppHealtHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbImagenAppHealtHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbImagenAppHealtHelpMouseClicked(evt);
            }
        });
        panel1.add(LbImagenAppHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        LbHealtHelp.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        LbHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbHealtHelp.setText("HealtHelp");
        panel1.add(LbHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        LbSloganHealtHelp.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        LbSloganHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbSloganHealtHelp.setText("Tu salud en nuestras manos ");
        panel1.add(LbSloganHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 15));

        LbEspecialidadDoctor.setFont(new java.awt.Font("Sitka Banner", 0, 16)); // NOI18N
        LbEspecialidadDoctor.setForeground(new java.awt.Color(199, 226, 221));
        LbEspecialidadDoctor.setText("Especialista en cardiología");
        panel1.add(LbEspecialidadDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 180, -1));

        LbImagenDoctorPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Armando mendoza.png"))); // NOI18N
        panel1.add(LbImagenDoctorPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 150));

        LbImagenCalificacionDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EstrellasValoracion.png"))); // NOI18N
        panel1.add(LbImagenCalificacionDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        LbNombreDoctorPerfil.setFont(new java.awt.Font("Sitka Banner", 1, 28)); // NOI18N
        LbNombreDoctorPerfil.setForeground(new java.awt.Color(209, 219, 228));
        LbNombreDoctorPerfil.setText("Dr. Armando Mendoza");
        panel1.add(LbNombreDoctorPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 260, -1));

        BnReservarCitaOpiniones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reservar Cita.png"))); // NOI18N
        BnReservarCitaOpiniones.setBorder(null);
        BnReservarCitaOpiniones.setBorderPainted(false);
        BnReservarCitaOpiniones.setContentAreaFilled(false);
        BnReservarCitaOpiniones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BnReservarCitaOpiniones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reservar Cita_ON.png"))); // NOI18N
        BnReservarCitaOpiniones.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reservar Cita_ON.png"))); // NOI18N
        BnReservarCitaOpiniones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnReservarCitaOpinionesActionPerformed(evt);
            }
        });
        panel1.add(BnReservarCitaOpiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 280, 90));

        Panel3Opiniones.setBorder(new org.edisoncor.gui.util.DropShadowBorder());
        Panel3Opiniones.setColorPrimario(new java.awt.Color(1, 122, 91));
        Panel3Opiniones.setColorSecundario(new java.awt.Color(1, 122, 91));
        Panel3Opiniones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxAgregaComentarioOpiniones.setBackground(new java.awt.Color(0, 71, 49));
        TxAgregaComentarioOpiniones.setForeground(new java.awt.Color(255, 255, 255));
        TxAgregaComentarioOpiniones.setBorderColor(new java.awt.Color(1, 122, 91));
        TxAgregaComentarioOpiniones.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        TxAgregaComentarioOpiniones.setPhColor(new java.awt.Color(255, 255, 255));
        TxAgregaComentarioOpiniones.setPlaceholder("Agrega un comentario aquí...");
        Panel3Opiniones.add(TxAgregaComentarioOpiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 260, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Foto usuario.png"))); // NOI18N
        Panel3Opiniones.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 40, 40));

        LbOpiniones.setFont(new java.awt.Font("Sitka Banner", 1, 28)); // NOI18N
        LbOpiniones.setForeground(new java.awt.Color(209, 219, 228));
        LbOpiniones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbOpiniones.setText("Opiniones de pacientes");
        Panel3Opiniones.add(LbOpiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, -1));

        TbOpiniones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Opinión"
            }
        ));
        TbOpiniones.setBackgoundHead(new java.awt.Color(255, 255, 255));
        TbOpiniones.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        TbOpiniones.setColorSecondary(new java.awt.Color(255, 255, 255));
        TbOpiniones.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        TbOpiniones.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TbOpiniones.setFontRowHover(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TbOpiniones.setFontRowSelect(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TbOpiniones.setForegroundHead(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(TbOpiniones);

        Panel3Opiniones.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 340, 220));

        BnEnviar.setBackground(new java.awt.Color(0, 81, 60));
        BnEnviar.setText("Enviar");
        BnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnEnviarActionPerformed(evt);
            }
        });
        Panel3Opiniones.add(BnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 80, 38));

        panel1.add(Panel3Opiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 370, 350));

        BnVolverOpiniones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonVolver.png"))); // NOI18N
        BnVolverOpiniones.setBorder(null);
        BnVolverOpiniones.setBorderPainted(false);
        BnVolverOpiniones.setContentAreaFilled(false);
        BnVolverOpiniones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BnVolverOpiniones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonVolver2 .png"))); // NOI18N
        BnVolverOpiniones.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BótonVolver2 .png"))); // NOI18N
        BnVolverOpiniones.setSelected(true);
        BnVolverOpiniones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnVolverOpinionesActionPerformed(evt);
            }
        });
        panel1.add(BnVolverOpiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 210, 70));

        LbNombrePacienteInterfaz3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbNombrePacienteInterfaz3.setForeground(new java.awt.Color(255, 255, 255));
        LbNombrePacienteInterfaz3.setText("Rosendo Bucuru");
        panel1.add(LbNombrePacienteInterfaz3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 180, 40));

        LbImagenUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Foto usuario.png"))); // NOI18N
        panel1.add(LbImagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 40, 40));

        LbCitasAgendadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCitasAgendadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.png"))); // NOI18N
        LbCitasAgendadas.setToolTipText("CITAS AGENDADAS");
        LbCitasAgendadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbCitasAgendadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCitasAgendadasMouseClicked(evt);
            }
        });
        panel1.add(LbCitasAgendadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 40, 40));

        LbEditarPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-pequeño.png"))); // NOI18N
        LbEditarPerfil.setToolTipText("EDITAR PERFIL");
        LbEditarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbEditarPerfilMouseClicked(evt);
            }
        });
        panel1.add(LbEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 40, 40));

        LbCerrarSesión.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCerrarSesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion-pequeño.png"))); // NOI18N
        LbCerrarSesión.setToolTipText("CERRAR SESIÓN");
        LbCerrarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbCerrarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCerrarSesiónMouseClicked(evt);
            }
        });
        panel1.add(LbCerrarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 40, 40));

        Panel2SobreElOpiniones.setBackground(new java.awt.Color(1, 122, 91));
        Panel2SobreElOpiniones.setBorder(new org.edisoncor.gui.util.DropShadowBorder());
        Panel2SobreElOpiniones.setColorPrimario(new java.awt.Color(0, 105, 78));
        Panel2SobreElOpiniones.setColorSecundario(new java.awt.Color(0, 105, 78));
        Panel2SobreElOpiniones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Sitka Banner", 1, 28)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(209, 219, 228));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Sobre él");
        Panel2SobreElOpiniones.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 260, -1));

        LbSobreEl1.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        LbSobreEl1.setForeground(new java.awt.Color(209, 227, 229));
        LbSobreEl1.setText("Soy un especialista en cardiología, poseo un postgrado y");
        Panel2SobreElOpiniones.add(LbSobreEl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        LbSobreEl2.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        LbSobreEl2.setForeground(new java.awt.Color(209, 227, 229));
        LbSobreEl2.setText("calificado con excelencia en el curso de mi doctorado.");
        Panel2SobreElOpiniones.add(LbSobreEl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        LbSobreEl3.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        LbSobreEl3.setForeground(new java.awt.Color(209, 227, 229));
        LbSobreEl3.setText("Mis estudios fueron enfocados en la prestigiosa universidad");
        Panel2SobreElOpiniones.add(LbSobreEl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel22.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(209, 227, 229));
        jLabel22.setText("univalle.");
        Panel2SobreElOpiniones.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        LbSobreEl5.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        LbSobreEl5.setForeground(new java.awt.Color(209, 227, 229));
        LbSobreEl5.setText("Soy una persona dedicada a mi trabajo, mi prioridad es la ");
        Panel2SobreElOpiniones.add(LbSobreEl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        LbSobreEl6.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        LbSobreEl6.setForeground(new java.awt.Color(209, 227, 229));
        LbSobreEl6.setText("vida y salud de mis pacientes...");
        Panel2SobreElOpiniones.add(LbSobreEl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        panel1.add(Panel2SobreElOpiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 450, 230));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LbCitasAgendadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCitasAgendadasMouseClicked

        HH_TablaCitasPaciente citasAgendadas = new HH_TablaCitasPaciente();
        citasAgendadas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbCitasAgendadasMouseClicked

    private void LbEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbEditarPerfilMouseClicked

        HH_Cambios editarperfilpaciente = new HH_Cambios();
        editarperfilpaciente.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbEditarPerfilMouseClicked

    private void LbCerrarSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCerrarSesiónMouseClicked

        MenuEntrada menu = new MenuEntrada();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbCerrarSesiónMouseClicked

    private void BnVolverOpinionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnVolverOpinionesActionPerformed
        HH_SoyMédico soymedico = new HH_SoyMédico();
        soymedico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BnVolverOpinionesActionPerformed

    private void LbImagenAppHealtHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbImagenAppHealtHelpMouseClicked

        HhAgendarCita principal = new HhAgendarCita();
        principal.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbImagenAppHealtHelpMouseClicked

    private void BnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnEnviarActionPerformed
        if (TxAgregaComentarioOpiniones.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes escribir una opinión para poder cargar");
        } ///////////////////////////////////////////////////////////////////////////////
        else {
            temporal pm = new temporal();
            int opcion = SqlOpiniones.opiniones(pm.getID(),pm.getNombre(), pm.getCorreoMedicoSeleccionado());
            SqlOpiniones.listarOpiniones(pm.getCorreoMedicoSeleccionado());
            if (opcion > 0) {

                HH_MensajeSuccessfulOpiniones successful = new HH_MensajeSuccessfulOpiniones(this, true);
                successful.setVisible(true);

                limpiarCampos();
            } else {

                HH_MensajeErrorOpiniones error = new HH_MensajeErrorOpiniones(this, true);
                error.setVisible(true);

                limpiarCampos();
            }
            this.limpiarCampos();
        }
    }//GEN-LAST:event_BnEnviarActionPerformed

    private void BnReservarCitaOpinionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnReservarCitaOpinionesActionPerformed
        
        HhAgendarCita agendarCita = new HhAgendarCita();
        agendarCita.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BnReservarCitaOpinionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HhOpiniones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HhOpiniones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HhOpiniones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HhOpiniones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HhOpiniones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static rojeru_san.RSButton BnEnviar;
    private javax.swing.JButton BnReservarCitaOpiniones;
    private javax.swing.JButton BnVolverOpiniones;
    private javax.swing.JLabel LbCerrarSesión;
    private javax.swing.JLabel LbCitasAgendadas;
    private javax.swing.JLabel LbEditarPerfil;
    public static javax.swing.JLabel LbEspecialidadDoctor;
    private javax.swing.JLabel LbHealtHelp;
    private javax.swing.JLabel LbImagenAppHealtHelp;
    private javax.swing.JLabel LbImagenCalificacionDoctor;
    public static javax.swing.JLabel LbImagenDoctorPerfil;
    public static javax.swing.JLabel LbImagenUsuario;
    public static javax.swing.JLabel LbNombreDoctorPerfil;
    public static javax.swing.JLabel LbNombrePacienteInterfaz3;
    private javax.swing.JLabel LbOpiniones;
    private javax.swing.JLabel LbSloganHealtHelp;
    private javax.swing.JLabel LbSobreEl1;
    private javax.swing.JLabel LbSobreEl2;
    private javax.swing.JLabel LbSobreEl3;
    private javax.swing.JLabel LbSobreEl5;
    private javax.swing.JLabel LbSobreEl6;
    private org.edisoncor.gui.panel.Panel Panel2SobreElOpiniones;
    private org.edisoncor.gui.panel.Panel Panel3Opiniones;
    public static RSMaterialComponent.RSTableMetroCustom TbOpiniones;
    public static RSMaterialComponent.RSTextFieldOne TxAgregaComentarioOpiniones;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
