/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author juanm
 */
public class Libre extends javax.swing.JFrame {

    /**
     * Creates new form Libre
     */
    public Libre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbxPasiente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxDisponibilidad = new javax.swing.JComboBox<>();
        cbxHora = new javax.swing.JComboBox<>();
        rdbMaculino = new javax.swing.JRadioButton();
        rdbFemenino = new javax.swing.JRadioButton();
        rdbOtro = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cbxTipoProblema = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTipoProblema = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        bnAgendar = new javax.swing.JButton();
        Panel3Opiniones = new org.edisoncor.gui.panel.Panel();
        TxAgregaComentarioOpiniones = new RSMaterialComponent.RSTextFieldOne();
        jLabel12 = new javax.swing.JLabel();
        LbOpiniones = new javax.swing.JLabel();
        LbNombreUsuario = new javax.swing.JLabel();
        LbOpinionUsuario2 = new javax.swing.JLabel();
        LbOpinionUsuario1 = new javax.swing.JLabel();
        LbNombreUsuarioOpiniones = new javax.swing.JLabel();
        LbOpinionUsuario5 = new javax.swing.JLabel();
        LbOpinionUsuario3 = new javax.swing.JLabel();
        LbOpinionUsuario4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HealtHelp");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tu salud en nuestras manos ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 40, -1, 15));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Agendar una cita");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 111, -1, -1));

        cbxPasiente.setBackground(new java.awt.Color(0, 204, 153));
        cbxPasiente.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        cbxPasiente.setForeground(new java.awt.Color(255, 255, 255));
        cbxPasiente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pasiente" }));
        jPanel2.add(cbxPasiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 22, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/male-profile-picture_icon-icons.com_68388.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 11, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Profesional de la salud");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Disponibilidad");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 208, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hora");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 264, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Genero");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 327, -1, -1));

        cbxDisponibilidad.setBackground(new java.awt.Color(0, 153, 102));
        cbxDisponibilidad.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cbxDisponibilidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel2.add(cbxDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 235, 66, -1));

        cbxHora.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jPanel2.add(cbxHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 289, 66, -1));

        rdbMaculino.setBackground(new java.awt.Color(0, 153, 102));
        rdbMaculino.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        rdbMaculino.setForeground(new java.awt.Color(255, 255, 255));
        rdbMaculino.setText("Maculino");
        jPanel2.add(rdbMaculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 352, -1, -1));

        rdbFemenino.setBackground(new java.awt.Color(0, 153, 102));
        rdbFemenino.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        rdbFemenino.setForeground(new java.awt.Color(255, 255, 255));
        rdbFemenino.setText("Femenino");
        jPanel2.add(rdbFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 352, -1, -1));

        rdbOtro.setBackground(new java.awt.Color(0, 153, 102));
        rdbOtro.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        rdbOtro.setForeground(new java.awt.Color(255, 255, 255));
        rdbOtro.setText("Otro");
        jPanel2.add(rdbOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 352, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo de probelma");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 154, -1, -1));

        cbxTipoProblema.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jPanel2.add(cbxTipoProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 176, 86, -1));

        txaTipoProblema.setColumns(20);
        txaTipoProblema.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        txaTipoProblema.setRows(5);
        jScrollPane1.setViewportView(txaTipoProblema);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 199, 111));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 153, 153));
        jTextField1.setText("Opcional");
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 170, 61, -1));

        bnAgendar.setBackground(new java.awt.Color(0, 153, 102));
        bnAgendar.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        bnAgendar.setForeground(new java.awt.Color(255, 255, 255));
        bnAgendar.setText("Agendar");
        jPanel2.add(bnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        Panel3Opiniones.setBorder(new org.edisoncor.gui.util.DropShadowBorder());
        Panel3Opiniones.setColorPrimario(new java.awt.Color(1, 122, 91));
        Panel3Opiniones.setColorSecundario(new java.awt.Color(1, 122, 91));
        Panel3Opiniones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxAgregaComentarioOpiniones.setBackground(new java.awt.Color(0, 71, 49));
        TxAgregaComentarioOpiniones.setForeground(new java.awt.Color(255, 255, 255));
        TxAgregaComentarioOpiniones.setBorderColor(new java.awt.Color(1, 122, 91));
        TxAgregaComentarioOpiniones.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        TxAgregaComentarioOpiniones.setPhColor(new java.awt.Color(255, 255, 255));
        TxAgregaComentarioOpiniones.setPlaceholder("Agrega un comentario aquí...");
        Panel3Opiniones.add(TxAgregaComentarioOpiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 340, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Foto usuario.png"))); // NOI18N
        Panel3Opiniones.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 40, 40));

        LbOpiniones.setFont(new java.awt.Font("Sitka Banner", 1, 28)); // NOI18N
        LbOpiniones.setForeground(new java.awt.Color(209, 219, 228));
        LbOpiniones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbOpiniones.setText("Opiniones de pacientes");
        Panel3Opiniones.add(LbOpiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, -1));

        LbNombreUsuario.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        LbNombreUsuario.setForeground(new java.awt.Color(209, 219, 228));
        LbNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbNombreUsuario.setText("Gustavo Petro");
        Panel3Opiniones.add(LbNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, -1));

        LbOpinionUsuario2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbOpinionUsuario2.setForeground(new java.awt.Color(209, 227, 229));
        LbOpinionUsuario2.setText("hasta los festivos desea y ejerce su labor.");
        Panel3Opiniones.add(LbOpinionUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 280, -1));

        LbOpinionUsuario1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbOpinionUsuario1.setForeground(new java.awt.Color(209, 227, 229));
        LbOpinionUsuario1.setText("Excelente, Armando es tan enfocado que ");
        Panel3Opiniones.add(LbOpinionUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 280, -1));

        LbNombreUsuarioOpiniones.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        LbNombreUsuarioOpiniones.setForeground(new java.awt.Color(209, 219, 228));
        LbNombreUsuarioOpiniones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbNombreUsuarioOpiniones.setText("Diana Marcela");
        Panel3Opiniones.add(LbNombreUsuarioOpiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 160, -1));

        LbOpinionUsuario5.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbOpinionUsuario5.setForeground(new java.awt.Color(209, 227, 229));
        LbOpinionUsuario5.setText("ahora será el que me atienda siempre.");
        Panel3Opiniones.add(LbOpinionUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 280, 20));

        LbOpinionUsuario3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbOpinionUsuario3.setForeground(new java.awt.Color(209, 227, 229));
        LbOpinionUsuario3.setText("Don Armando maneja un buen entusiasmo");
        Panel3Opiniones.add(LbOpinionUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 280, -1));

        LbOpinionUsuario4.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbOpinionUsuario4.setForeground(new java.awt.Color(209, 227, 229));
        LbOpinionUsuario4.setText("por ayudar a sus pacientes. A partir de");
        Panel3Opiniones.add(LbOpinionUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 280, -1));

        jPanel2.add(Panel3Opiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 360, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Libre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Libre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Libre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Libre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Libre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbNombreUsuario;
    private javax.swing.JLabel LbNombreUsuarioOpiniones;
    private javax.swing.JLabel LbOpinionUsuario1;
    private javax.swing.JLabel LbOpinionUsuario2;
    private javax.swing.JLabel LbOpinionUsuario3;
    private javax.swing.JLabel LbOpinionUsuario4;
    private javax.swing.JLabel LbOpinionUsuario5;
    private javax.swing.JLabel LbOpiniones;
    private org.edisoncor.gui.panel.Panel Panel3Opiniones;
    private RSMaterialComponent.RSTextFieldOne TxAgregaComentarioOpiniones;
    private javax.swing.JButton bnAgendar;
    private javax.swing.JComboBox<String> cbxDisponibilidad;
    private javax.swing.JComboBox<String> cbxHora;
    private javax.swing.JComboBox<String> cbxPasiente;
    private javax.swing.JComboBox<String> cbxTipoProblema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rdbFemenino;
    private javax.swing.JRadioButton rdbMaculino;
    private javax.swing.JRadioButton rdbOtro;
    private javax.swing.JTextArea txaTipoProblema;
    // End of variables declaration//GEN-END:variables
}
