/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.conectarBD;
import java.awt.Desktop;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.net.URI;
import java.sql.Connection;

/**
 *
 * @author David
 */
public class MenuEntrada extends javax.swing.JFrame {

    conectarBD con;
    /**
     * Creates new form MenuEntrada
     */
    public MenuEntrada() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Shape forma = new RoundRectangle2D.Double(0,0,this.getBounds().width,this.getBounds().height,50,50);
        //AWTUtilities.setWindowShape(this, forma);
        con = new conectarBD();
        Connection reg = con.getConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAgendarCita = new org.edisoncor.gui.panel.Panel();
        jSeparator1 = new javax.swing.JSeparator();
        LbLogo = new javax.swing.JLabel();
        LbSloganHealtHelp = new javax.swing.JLabel();
        LbTituloHealtHelp = new javax.swing.JLabel();
        BnIngresar = new rojerusan.RSMaterialButtonRectangle();
        BnRegistrarse = new rojerusan.RSMaterialButtonRectangle();
        LbMinimizar = new javax.swing.JLabel();
        LbSalir = new javax.swing.JLabel();
        LbTituloHealtHelp1 = new javax.swing.JLabel();
        LbTituloHealtHelp2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PaginaWeb = new javax.swing.JLabel();
        Facebook = new javax.swing.JLabel();
        Instagram = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAgendarCita.setColorPrimario(new java.awt.Color(0, 102, 153));
        PanelAgendarCita.setColorSecundario(new java.awt.Color(0, 153, 102));
        PanelAgendarCita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelAgendarCita.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 189, -1, -1));

        LbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoAppGRANDERecortado.png"))); // NOI18N
        PanelAgendarCita.add(LbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 270, 260));

        LbSloganHealtHelp.setFont(new java.awt.Font("Segoe Script", 3, 16)); // NOI18N
        LbSloganHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbSloganHealtHelp.setText("Tu salud en nuestras manos ");
        PanelAgendarCita.add(LbSloganHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, 15));

        LbTituloHealtHelp.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        LbTituloHealtHelp.setForeground(new java.awt.Color(255, 255, 255));
        LbTituloHealtHelp.setText("A LA WEB DE CITAS");
        PanelAgendarCita.add(LbTituloHealtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        BnIngresar.setBackground(new java.awt.Color(255, 255, 255));
        BnIngresar.setForeground(new java.awt.Color(0, 153, 153));
        BnIngresar.setText("Ingresar");
        BnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnIngresarActionPerformed(evt);
            }
        });
        PanelAgendarCita.add(BnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 160, 50));

        BnRegistrarse.setBackground(new java.awt.Color(255, 255, 255));
        BnRegistrarse.setForeground(new java.awt.Color(0, 153, 153));
        BnRegistrarse.setText("Registrarse");
        BnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnRegistrarseActionPerformed(evt);
            }
        });
        PanelAgendarCita.add(BnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 160, 50));

        LbMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar (1).png"))); // NOI18N
        LbMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbMinimizarMouseClicked(evt);
            }
        });
        PanelAgendarCita.add(LbMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 40, 40));

        LbSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir (1).png"))); // NOI18N
        LbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbSalirMouseClicked(evt);
            }
        });
        PanelAgendarCita.add(LbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 40, 40));

        LbTituloHealtHelp1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        LbTituloHealtHelp1.setForeground(new java.awt.Color(255, 255, 255));
        LbTituloHealtHelp1.setText("HEALTHELP");
        PanelAgendarCita.add(LbTituloHealtHelp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        LbTituloHealtHelp2.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        LbTituloHealtHelp2.setForeground(new java.awt.Color(255, 255, 255));
        LbTituloHealtHelp2.setText("BIENVENIDOS");
        PanelAgendarCita.add(LbTituloHealtHelp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ó");
        PanelAgendarCita.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 50, -1));

        PaginaWeb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PaginaWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Web.png"))); // NOI18N
        PaginaWeb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PaginaWeb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaginaWebMouseClicked(evt);
            }
        });
        PanelAgendarCita.add(PaginaWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 40, 40));

        Facebook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/facebook.png"))); // NOI18N
        Facebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Facebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacebookMouseClicked(evt);
            }
        });
        PanelAgendarCita.add(Facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 40, 40));

        Instagram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Instagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/instagram.png"))); // NOI18N
        Instagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Instagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstagramMouseClicked(evt);
            }
        });
        PanelAgendarCita.add(Instagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 40, 40));

        getContentPane().add(PanelAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 610));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/X.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 40, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/X.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 40, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnIngresarActionPerformed
    
        ElegirPerfil elegirperfil = new ElegirPerfil();
        elegirperfil.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_BnIngresarActionPerformed

    private void BnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnRegistrarseActionPerformed
    
        HH_ElegirCuenta registrohp = new HH_ElegirCuenta();
        registrohp.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BnRegistrarseActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void LbMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbMinimizarMouseClicked
    
        this.setState(MenuEntrada.ICONIFIED);
        
    }//GEN-LAST:event_LbMinimizarMouseClicked

    private void LbSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbSalirMouseClicked

        System.exit(0);
        
    }//GEN-LAST:event_LbSalirMouseClicked

    private void FacebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacebookMouseClicked
        
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://www.facebook.com/COhealthelp"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_FacebookMouseClicked

    private void InstagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstagramMouseClicked
        
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://www.instagram.com/realite_company/"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_InstagramMouseClicked

    private void PaginaWebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaginaWebMouseClicked
        
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://softwarerealite202.wixsite.com/website"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_PaginaWebMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle BnIngresar;
    private rojerusan.RSMaterialButtonRectangle BnRegistrarse;
    private javax.swing.JLabel Facebook;
    private javax.swing.JLabel Instagram;
    private javax.swing.JLabel LbLogo;
    private javax.swing.JLabel LbMinimizar;
    private javax.swing.JLabel LbSalir;
    private javax.swing.JLabel LbSloganHealtHelp;
    private javax.swing.JLabel LbTituloHealtHelp;
    private javax.swing.JLabel LbTituloHealtHelp1;
    private javax.swing.JLabel LbTituloHealtHelp2;
    private javax.swing.JLabel PaginaWeb;
    private org.edisoncor.gui.panel.Panel PanelAgendarCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
