/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.SqlRegistroPaciente;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import rojerusan.RSNotifyShadowAnimated;

/**
 *
 * @author juanm
 */
public class RegistroHP extends javax.swing.JFrame {

    public static Blob imagen2;

    int num;
    public static FileInputStream imagen;
    public int longitudBytes;
    public static String tipoDocumento;
    public static String eps;

    /**
     * Creates new form RegistroHP
     */
    public RegistroHP() {
        initComponents();
        this.setLocationRelativeTo(null);
        LbImagenCargar.setVisible(false);
    }

    private void limpiarCampos() {

        this.CbxTipoDocumentoRegistro.setSelectedIndex(0);
        this.TxNumeroDocumentoRegistro.setText("");
        this.RSCalendarFechaNacimientoRegistro.setDatoFecha(null);
        this.CbxEpsRegistro.setSelectedIndex(0);
        this.TxNumeroTelefonoRegistro.setText("");
        this.TxCelularRegistro.setText("");
        this.TxNombreRegistro.setText("");
        this.TxApellidoRegistro.setText("");
        this.TxCorreoElectronicoRegistro.setText("");
        this.TxContraseñaRegistro.setText("");
        this.LbImagenCargar.setIcon(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRect1 = new org.edisoncor.gui.label.LabelRect();
        PanelRegistro = new org.edisoncor.gui.panel.Panel();
        jSeparator1 = new javax.swing.JSeparator();
        LbTituloRegistro = new javax.swing.JLabel();
        RSCalendarFechaNacimientoRegistro = new rojeru_san.componentes.RSDateChooser();
        TxNumeroDocumentoRegistro = new RSMaterialComponent.RSTextFieldIconOne();
        CbxEpsRegistro = new RSMaterialComponent.RSComboBox();
        CbxTipoDocumentoRegistro = new RSMaterialComponent.RSComboBox();
        TxNumeroTelefonoRegistro = new RSMaterialComponent.RSTextFieldIconOne();
        TxCelularRegistro = new RSMaterialComponent.RSTextFieldIconOne();
        TxNombreRegistro = new RSMaterialComponent.RSTextFieldIconOne();
        TxCorreoElectronicoRegistro = new RSMaterialComponent.RSTextFieldIconOne();
        BnSalir = new rojerusan.RSMaterialButtonRectangle();
        BnRegistrarseRegistro1 = new rojerusan.RSMaterialButtonRectangle();
        TxContraseñaRegistro = new RSMaterialComponent.RSPasswordIconOne();
        panel1 = new org.edisoncor.gui.panel.Panel();
        BnCargarImagenPerfilPaciente = new rojerusan.RSMaterialButtonRectangle();
        LbProfesionalSaludAgendarCita1 = new javax.swing.JLabel();
        LbImagenCargar = new javax.swing.JLabel();
        TxApellidoRegistro = new RSMaterialComponent.RSTextFieldIconOne();

        labelRect1.setText("labelRect1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        PanelRegistro.setColorPrimario(new java.awt.Color(0, 102, 153));
        PanelRegistro.setColorSecundario(new java.awt.Color(0, 153, 102));
        PanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelRegistro.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 190, -1, -1));

        LbTituloRegistro.setFont(new java.awt.Font("Century Gothic", 3, 56)); // NOI18N
        LbTituloRegistro.setForeground(new java.awt.Color(255, 255, 255));
        LbTituloRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbTituloRegistro.setText("REGISTRO");
        PanelRegistro.add(LbTituloRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 320, -1));

        RSCalendarFechaNacimientoRegistro.setColorForeground(new java.awt.Color(0, 0, 0));
        RSCalendarFechaNacimientoRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RSCalendarFechaNacimientoRegistro.setPlaceholder("Fecha de nacimiento.");
        PanelRegistro.add(RSCalendarFechaNacimientoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 350, -1));

        TxNumeroDocumentoRegistro.setForeground(new java.awt.Color(0, 0, 0));
        TxNumeroDocumentoRegistro.setBorderColor(new java.awt.Color(255, 255, 255));
        TxNumeroDocumentoRegistro.setColorIcon(new java.awt.Color(0, 0, 0));
        TxNumeroDocumentoRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxNumeroDocumentoRegistro.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DESCRIPTION);
        TxNumeroDocumentoRegistro.setPlaceholder("Número de documento.");
        TxNumeroDocumentoRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxNumeroDocumentoRegistroKeyTyped(evt);
            }
        });
        PanelRegistro.add(TxNumeroDocumentoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 350, 40));

        CbxEpsRegistro.setForeground(new java.awt.Color(0, 0, 0));
        CbxEpsRegistro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\t                                              Eps.", "                                            S.O.S", "                                            SURA", "                                         SANITAS", "                                            OTRO" }));
        CbxEpsRegistro.setColorArrow(new java.awt.Color(0, 0, 0));
        CbxEpsRegistro.setColorBorde(new java.awt.Color(255, 255, 255));
        CbxEpsRegistro.setColorBoton(new java.awt.Color(255, 255, 255));
        CbxEpsRegistro.setColorFondo(new java.awt.Color(255, 255, 255));
        CbxEpsRegistro.setColorSeleccion(new java.awt.Color(0, 150, 157));
        PanelRegistro.add(CbxEpsRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 350, 40));

        CbxTipoDocumentoRegistro.setForeground(new java.awt.Color(0, 0, 0));
        CbxTipoDocumentoRegistro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\t                               Tipo de documento.    ", "                                            Cédula", "                                               NIT", "                                         Pasaporte" }));
        CbxTipoDocumentoRegistro.setColorArrow(new java.awt.Color(0, 0, 0));
        CbxTipoDocumentoRegistro.setColorBoton(new java.awt.Color(255, 255, 255));
        CbxTipoDocumentoRegistro.setColorFondo(new java.awt.Color(255, 255, 255));
        CbxTipoDocumentoRegistro.setColorSeleccion(new java.awt.Color(0, 102, 204));
        PanelRegistro.add(CbxTipoDocumentoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 350, 40));

        TxNumeroTelefonoRegistro.setForeground(new java.awt.Color(0, 0, 0));
        TxNumeroTelefonoRegistro.setBorderColor(new java.awt.Color(255, 255, 255));
        TxNumeroTelefonoRegistro.setColorIcon(new java.awt.Color(0, 0, 0));
        TxNumeroTelefonoRegistro.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        TxNumeroTelefonoRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxNumeroTelefonoRegistro.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CALL);
        TxNumeroTelefonoRegistro.setPlaceholder("Número de teléfono.");
        TxNumeroTelefonoRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxNumeroTelefonoRegistroKeyTyped(evt);
            }
        });
        PanelRegistro.add(TxNumeroTelefonoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 350, 40));

        TxCelularRegistro.setForeground(new java.awt.Color(0, 0, 0));
        TxCelularRegistro.setBorderColor(new java.awt.Color(255, 255, 255));
        TxCelularRegistro.setColorIcon(new java.awt.Color(0, 0, 0));
        TxCelularRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxCelularRegistro.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PHONE_ANDROID);
        TxCelularRegistro.setPlaceholder("Número de celular.");
        TxCelularRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxCelularRegistroKeyTyped(evt);
            }
        });
        PanelRegistro.add(TxCelularRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 350, 40));

        TxNombreRegistro.setForeground(new java.awt.Color(0, 0, 0));
        TxNombreRegistro.setBorderColor(new java.awt.Color(255, 255, 255));
        TxNombreRegistro.setColorIcon(new java.awt.Color(0, 0, 0));
        TxNombreRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxNombreRegistro.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        TxNombreRegistro.setPlaceholder("Nombre.");
        PanelRegistro.add(TxNombreRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 350, 40));

        TxCorreoElectronicoRegistro.setForeground(new java.awt.Color(0, 0, 0));
        TxCorreoElectronicoRegistro.setBorderColor(new java.awt.Color(255, 255, 255));
        TxCorreoElectronicoRegistro.setColorIcon(new java.awt.Color(0, 0, 0));
        TxCorreoElectronicoRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxCorreoElectronicoRegistro.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EMAIL);
        TxCorreoElectronicoRegistro.setPlaceholder("Correo electrónico.");
        TxCorreoElectronicoRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxCorreoElectronicoRegistroFocusLost(evt);
            }
        });
        PanelRegistro.add(TxCorreoElectronicoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 350, 40));

        BnSalir.setBackground(new java.awt.Color(255, 255, 255));
        BnSalir.setForeground(new java.awt.Color(0, 0, 0));
        BnSalir.setText("Salir");
        BnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnSalirActionPerformed(evt);
            }
        });
        PanelRegistro.add(BnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, 120, 50));

        BnRegistrarseRegistro1.setBackground(new java.awt.Color(255, 255, 255));
        BnRegistrarseRegistro1.setForeground(new java.awt.Color(0, 0, 0));
        BnRegistrarseRegistro1.setText("REGISTRARSE");
        BnRegistrarseRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnRegistrarseRegistro1ActionPerformed(evt);
            }
        });
        PanelRegistro.add(BnRegistrarseRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 130, 50));

        TxContraseñaRegistro.setForeground(new java.awt.Color(0, 0, 0));
        TxContraseñaRegistro.setBorderColor(new java.awt.Color(255, 255, 255));
        TxContraseñaRegistro.setColorIcon(new java.awt.Color(0, 0, 0));
        TxContraseñaRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxContraseñaRegistro.setPlaceholder("Contraseña.");
        PanelRegistro.add(TxContraseñaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 350, 40));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panel1.setForeground(new java.awt.Color(255, 255, 255));
        panel1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BnCargarImagenPerfilPaciente.setBackground(new java.awt.Color(255, 255, 255));
        BnCargarImagenPerfilPaciente.setForeground(new java.awt.Color(0, 0, 0));
        BnCargarImagenPerfilPaciente.setText("EXAMINAR");
        BnCargarImagenPerfilPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnCargarImagenPerfilPacienteActionPerformed(evt);
            }
        });
        panel1.add(BnCargarImagenPerfilPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 100, 40));

        LbProfesionalSaludAgendarCita1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbProfesionalSaludAgendarCita1.setForeground(new java.awt.Color(178, 181, 244));
        LbProfesionalSaludAgendarCita1.setText("Cargar imagen perfil");
        panel1.add(LbProfesionalSaludAgendarCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, -1));

        LbImagenCargar.setFont(new java.awt.Font("Algerian", 2, 16)); // NOI18N
        LbImagenCargar.setForeground(new java.awt.Color(255, 255, 255));
        panel1.add(LbImagenCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 150, 150));

        PanelRegistro.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 350, 40));

        TxApellidoRegistro.setForeground(new java.awt.Color(0, 0, 0));
        TxApellidoRegistro.setBorderColor(new java.awt.Color(255, 255, 255));
        TxApellidoRegistro.setColorIcon(new java.awt.Color(0, 0, 0));
        TxApellidoRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxApellidoRegistro.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        TxApellidoRegistro.setPlaceholder("Apellido.");
        PanelRegistro.add(TxApellidoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 350, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnSalirActionPerformed

        MenuEntrada menuentrada = new MenuEntrada();
        menuentrada.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BnSalirActionPerformed

    private void BnCargarImagenPerfilPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnCargarImagenPerfilPacienteActionPerformed

        JFileChooser se = new JFileChooser();
        FileNameExtensionFilter extension = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        se.setFileFilter(extension);
        int estado = se.showOpenDialog(this);
        System.out.print(estado);
        if (estado == JFileChooser.APPROVE_OPTION) {
            try {

                imagen = new FileInputStream(se.getSelectedFile());
                longitudBytes = (int) se.getSelectedFile().length();

                Image icono = ImageIO.read(se.getSelectedFile()).getScaledInstance(LbImagenCargar.getWidth(), LbImagenCargar.getHeight(), Image.SCALE_DEFAULT);
                LbImagenCargar.setIcon(new ImageIcon(icono));
                LbImagenCargar.updateUI();

            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_BnCargarImagenPerfilPacienteActionPerformed

    private void BnRegistrarseRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnRegistrarseRegistro1ActionPerformed

        Date fecha = RSCalendarFechaNacimientoRegistro.getDatoFecha();

        if (CbxTipoDocumentoRegistro.getSelectedIndex() == 0) {
            HH_MensajeError error = new HH_MensajeError(this, true);
            HH_MensajeError.Lb1.setText("Debes seleccionar un tipo de documento.");
            HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
            error.setVisible(true);
        } ///////////////////////////////////////////////////////////////////////////////////
        else if (TxNumeroDocumentoRegistro.getText().isEmpty()) {
            HH_MensajeError error = new HH_MensajeError(this, true);
            HH_MensajeError.Lb1.setText("Debes digitar un número de documento.");
            HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
            error.setVisible(true);
        } ///////////////////////////////////////////////////////////////////////////////
        else if (fecha == null) {
            HH_MensajeError error = new HH_MensajeError(this, true);
            HH_MensajeError.Lb1.setText("Debes digitar tu fecha de nacimiento.");
            HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
            error.setVisible(true);
        } ///////////////////////////////////////////////////////////////////////////////
        else if (CbxEpsRegistro.getSelectedIndex() == 0) {
            HH_MensajeError error = new HH_MensajeError(this, true);
            HH_MensajeError.Lb1.setText("Debes seleccionar tu eps.");
            HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
            error.setVisible(true);
        } ///////////////////////////////////////////////////////////////////////////////////
        else if (TxNumeroTelefonoRegistro.getText().isEmpty()) {
            HH_MensajeError error = new HH_MensajeError(this, true);
            HH_MensajeError.Lb1.setText("Debes digitar tu número de teléfono.");
            HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
            error.setVisible(true);
        } ///////////////////////////////////////////////////////////////////////////////
        else if (TxCelularRegistro.getText().isEmpty()) {
            HH_MensajeError error = new HH_MensajeError(this, true);
            HH_MensajeError.Lb1.setText("Debes digitar tu número de celular.");
            HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
            error.setVisible(true);
        } /////////////////////////////////////////////////////////////////////////////
        else if (TxNombreRegistro.getText().isEmpty()) {
            HH_MensajeError error = new HH_MensajeError(this, true);
            HH_MensajeError.Lb1.setText("Debes digitar tu nombre obligatoriamente.");
            HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
            error.setVisible(true);
        } /////////////////////////////////////////////////////////////////////////////
        else if (TxApellidoRegistro.getText().isEmpty()) {
            HH_MensajeError error = new HH_MensajeError(this, true);
            HH_MensajeError.Lb1.setText("Debes digitar tu apellido obligatoriamente.");
            HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
            error.setVisible(true);
        } /////////////////////////////////////////////////////////////////////////////
        else if (TxCorreoElectronicoRegistro.getText().isEmpty()) {
            HH_MensajeError error = new HH_MensajeError(this, true);
            HH_MensajeError.Lb1.setText("No puedes dejar el campo correo vacio.");
            HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
            error.setVisible(true);
        } /////////////////////////////////////////////////////////////////////////////
        else if (TxContraseñaRegistro.getText().isEmpty()) {
            HH_MensajeError error = new HH_MensajeError(this, true);
            HH_MensajeError.Lb1.setText("No puedes dejar el campo contraseña vacio.");
            HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
            error.setVisible(true);
        } /////////////////////////////////////////////////////////////////////////////
        else if (LbImagenCargar.getIcon() == null) {
            HH_MensajeError error = new HH_MensajeError(this, true);
            HH_MensajeError.Lb1.setText("Debes cargar una imagen de perfil.");
            HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
            error.setVisible(true);
        } /////////////////////////////////////////////////////////////////////////////        
        else {
            tipoDocumento = CbxTipoDocumentoRegistro.getSelectedItem().toString().trim();
            eps = CbxEpsRegistro.getSelectedItem().toString().trim();
            int opcion = SqlRegistroPaciente.guardar();
            if (opcion > 0) {
                HH_MensajeSuccessful error = new HH_MensajeSuccessful(this, true);
                HH_MensajeSuccessful.L1.setText("El registro se ha realizado con exito.");
                HH_MensajeSuccessful.L2.setText("Puedes iniciar sesión con tus datos.");
                error.setVisible(true);
                limpiarCampos();
            } else {
                HH_MensajeError error = new HH_MensajeError(this, true);
                HH_MensajeError.Lb1.setText("Ha ocurrido un error al realizar el registro.");
                HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
                error.setVisible(true);
                limpiarCampos();
            }
            this.limpiarCampos();

        }


    }//GEN-LAST:event_BnRegistrarseRegistro1ActionPerformed

    private void TxNumeroDocumentoRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNumeroDocumentoRegistroKeyTyped

        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_TxNumeroDocumentoRegistroKeyTyped

    private void TxNumeroTelefonoRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNumeroTelefonoRegistroKeyTyped

        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_TxNumeroTelefonoRegistroKeyTyped

    private void TxCelularRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCelularRegistroKeyTyped

        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_TxCelularRegistroKeyTyped

    private void TxCorreoElectronicoRegistroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxCorreoElectronicoRegistroFocusLost

        if (!TxCorreoElectronicoRegistro.getText().contains("@") || !TxCorreoElectronicoRegistro.getText().contains(".")) {
            HH_MensajeError error = new HH_MensajeError(this, true);
            HH_MensajeError.Lb1.setText("Correo electronico.");
            HH_MensajeError.Lb2.setText("Vuelve a intentarlo nuevamente.");
            error.setVisible(true);
        }

    }//GEN-LAST:event_TxCorreoElectronicoRegistroFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroHP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle BnCargarImagenPerfilPaciente;
    private rojerusan.RSMaterialButtonRectangle BnRegistrarseRegistro1;
    private rojerusan.RSMaterialButtonRectangle BnSalir;
    public static RSMaterialComponent.RSComboBox CbxEpsRegistro;
    public static RSMaterialComponent.RSComboBox CbxTipoDocumentoRegistro;
    public static javax.swing.JLabel LbImagenCargar;
    private javax.swing.JLabel LbProfesionalSaludAgendarCita1;
    private javax.swing.JLabel LbTituloRegistro;
    private org.edisoncor.gui.panel.Panel PanelRegistro;
    public static rojeru_san.componentes.RSDateChooser RSCalendarFechaNacimientoRegistro;
    public static RSMaterialComponent.RSTextFieldIconOne TxApellidoRegistro;
    public static RSMaterialComponent.RSTextFieldIconOne TxCelularRegistro;
    public static RSMaterialComponent.RSPasswordIconOne TxContraseñaRegistro;
    public static RSMaterialComponent.RSTextFieldIconOne TxCorreoElectronicoRegistro;
    public static RSMaterialComponent.RSTextFieldIconOne TxNombreRegistro;
    public static RSMaterialComponent.RSTextFieldIconOne TxNumeroDocumentoRegistro;
    public static RSMaterialComponent.RSTextFieldIconOne TxNumeroTelefonoRegistro;
    private javax.swing.JSeparator jSeparator1;
    private org.edisoncor.gui.label.LabelRect labelRect1;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
